package model

import (
	"errors"
	"fmt"
	"net/url"
)

// SiteConfig is the concise operator-authored v0.4 configuration. Expanded
// components and resolved module state are generated by the composition layer
// and are deliberately not accepted from site.yml.
type SiteConfig struct {
	// APIVersion identifies the operator-facing configuration contract.
	APIVersion string `yaml:"api_version" json:"api_version" jsonschema:"const=boetticher/v3" jsonschema_description:"Operator-facing configuration contract identifier."`
	// PlatformVersion is the Boetticher release targeted by this site.
	PlatformVersion string `yaml:"platform_version" json:"platform_version,omitempty" jsonschema:"const=0.4.0" jsonschema_description:"Boetticher platform release targeted by this site."`
	// SchemaVersion identifies the shape of the operator-facing site file.
	SchemaVersion int `yaml:"schema_version" json:"schema_version,omitempty" jsonschema:"const=3" jsonschema_description:"Shape version of the operator-authored site file."`
	// StorageProfile chooses the fixed single-disk or dedicated-data-disk layout.
	StorageProfile string `yaml:"storage_profile" json:"storage_profile,omitempty" jsonschema:"enum=single-disk,enum=dedicated-data-disk" jsonschema_description:"Fixed storage layout: the system disk or a separate dedicated data disk."`
	// StorageDevice names the stable device used by the dedicated data layout.
	StorageDevice string `yaml:"storage_device,omitempty" json:"storage_device,omitempty" jsonschema_description:"Stable /dev/disk/by-id identity for dedicated data storage."`
	// Gateway selects the managed gateway or the external-firewall contract.
	Gateway Gateway `yaml:"gateway" json:"gateway,omitempty" jsonschema_description:"Gateway mode and the existing upstream connection contract."`
	// BootstrapAddress records the known HOME-side address of the Proxmox host.
	BootstrapAddress string `yaml:"bootstrap_address,omitempty" json:"bootstrap_address,omitempty"`
	// SSHIdentityFile optionally overrides the controller SSH identity.
	SSHIdentityFile string `yaml:"ssh_identity_file,omitempty" json:"ssh_identity_file,omitempty"`
	// PhysicalNetwork records installation-specific NIC bindings separately from the logical network.
	PhysicalNetwork PhysicalNetwork `yaml:"physical_network" json:"physical_network,omitempty" jsonschema_description:"Installation-specific NIC bindings; the logical VLAN architecture is fixed."`
	// TestedVersions records the pinned platform inputs used by this site.
	TestedVersions TestedVersions `yaml:"tested_versions" json:"tested_versions,omitempty"`
	// Network contains the fixed private domain and zone contract.
	Network Network `yaml:"network" json:"network,omitempty" jsonschema_description:"Private domain and fixed network-zone contract."`
	// PKI contains public certificate metadata; private keys remain outside site.yml.
	PKI PKIMetadata `yaml:"pki" json:"pki,omitempty"`
	// SecretMetadata identifies encrypted-secret ownership without storing secret values.
	SecretMetadata SecretMetadata `yaml:"secret_metadata" json:"secret_metadata,omitempty"`
	// Ownership records the fixed resource ranges and workload boundary.
	Ownership OwnershipPolicy `yaml:"ownership" json:"ownership,omitempty"`
	// Modules is the authoritative typed configuration for built-in modules.
	Modules ModulesConfig `yaml:"modules,omitempty" json:"modules,omitempty" jsonschema_description:"Authoritative typed configuration for built-in modules."`
	// USBExports records stable physical-port bindings for declared module requirements.
	USBExports []USBExportBinding `yaml:"usb_exports,omitempty" json:"usb_exports,omitempty"`
	// DHCPReservations records explicit SERVERS reservations for user workloads.
	DHCPReservations []DHCPReservation `yaml:"dhcp_reservations,omitempty" json:"dhcp_reservations,omitempty"`
	// DNSRecords records user-owned A and CNAME records in the private namespace.
	DNSRecords []UserDNSRecord `yaml:"dns_records,omitempty" json:"dns_records,omitempty"`
	// UserFirewallRules records bounded user-workload policy additions.
	UserFirewallRules []UserFirewallRule `yaml:"firewall_rules,omitempty" json:"firewall_rules,omitempty"`
}

// ModulesConfig is the authoritative operator-facing module configuration.
// Each built-in module owns a typed configuration shape; the resolved Site
// keeps a small internal projection for providers that only need lookup by
// module name.
type ModulesConfig struct {
	DNS           *DNSModuleConfig       `yaml:"dns,omitempty" json:"dns,omitempty"`
	Monitoring    *ToggleModuleConfig    `yaml:"monitoring,omitempty" json:"monitoring,omitempty"`
	Firewall      *ToggleModuleConfig    `yaml:"firewall,omitempty" json:"firewall,omitempty"`
	Logging       *MandatoryModuleConfig `yaml:"logging,omitempty" json:"logging,omitempty"`
	TailnetRouter *ToggleModuleConfig    `yaml:"tailnet-router,omitempty" json:"tailnet-router,omitempty"`
	LiteLLM       *LiteLLMModuleConfig   `yaml:"litellm,omitempty" json:"litellm,omitempty"`
	Printer       *ToggleModuleConfig    `yaml:"printer,omitempty" json:"printer,omitempty"`
	AIOps         *AIOpsModuleConfig     `yaml:"aiops,omitempty" json:"aiops,omitempty"`
	Gatus         *ToggleModuleConfig    `yaml:"gatus,omitempty" json:"gatus,omitempty"`
}

// ModuleConfigField describes one operator-facing decision in a first-party
// module contract. It is metadata for the generic configure UX; the typed
// module structs below remain the only persisted configuration representation.
type ModuleConfigField struct {
	Key           string                `json:"key"`
	Type          ModuleConfigFieldType `json:"type"`
	Prompt        string                `json:"prompt"`
	Description   string                `json:"description,omitempty"`
	Required      bool                  `json:"required,omitempty"`
	Default       string                `json:"default,omitempty"`
	Sensitive     bool                  `json:"sensitive,omitempty"`
	AllowedValues []string              `json:"allowed_values,omitempty"`
	Resolver      string                `json:"resolver,omitempty"`
	MinItems      int                   `json:"min_items,omitempty"`
	MaxItems      int                   `json:"max_items,omitempty"`
	ItemFields    []ModuleConfigField   `json:"item_fields,omitempty"`
}

type ModuleConfigFieldType string

const (
	ModuleConfigBool       ModuleConfigFieldType = "bool"
	ModuleConfigString     ModuleConfigFieldType = "string"
	ModuleConfigEnum       ModuleConfigFieldType = "enum"
	ModuleConfigModelAlias ModuleConfigFieldType = "model-alias"
	ModuleConfigObjectList ModuleConfigFieldType = "object-list"
)

// DNSModuleConfig is intentionally empty: Blocky is the sole built-in DNS
// implementation and does not need an operator-selected provider field.
type DNSModuleConfig struct{}

// MandatoryModuleConfig intentionally has no enable field. Its empty typed
// shape makes modules.logging: {} valid while strict decoding rejects any
// operator attempt to persist lifecycle state for a mandatory module.
type MandatoryModuleConfig struct{}

type ToggleModuleConfig struct {
	// Enabled selects whether an optional module should be deployed.
	Enabled *bool `yaml:"enabled,omitempty" json:"enabled,omitempty"`
}

type LiteLLMModuleConfig struct {
	// Enabled selects whether the AI router should be deployed.
	Enabled *bool `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	// Upstreams declares HTTPS provider endpoints and references to encrypted credentials.
	Upstreams []LiteLLMUpstreamConfig `yaml:"upstreams,omitempty" json:"upstreams,omitempty"`
	// Models declares the provider-neutral aliases clients may request.
	Models []LiteLLMModelConfig `yaml:"models,omitempty" json:"models,omitempty"`
}

type LiteLLMUpstreamConfig struct {
	Name         string `yaml:"name" json:"name"`
	BaseURL      string `yaml:"base_url" json:"base_url"`
	APIKeySecret string `yaml:"api_key_secret" json:"api_key_secret"`
}

type LiteLLMModelConfig struct {
	Alias    string `yaml:"alias" json:"alias"`
	Upstream string `yaml:"upstream" json:"upstream"`
	Model    string `yaml:"model" json:"model"`
}

type AIOpsModuleConfig struct {
	Enabled    *bool  `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	ModelAlias string `yaml:"model_alias" json:"model_alias"`
}

// Map returns the normalized internal lookup projection. It is deliberately
// not used as the persisted SiteConfig representation.
func (m ModulesConfig) Map() map[string]ModuleConfig {
	result := make(map[string]ModuleConfig)
	if m.DNS != nil {
		result["dns"] = ModuleConfig{}
	}
	if m.Monitoring != nil {
		result["monitoring"] = ModuleConfig{Enabled: cloneBool(m.Monitoring.Enabled)}
	}
	if m.Firewall != nil {
		result["firewall"] = ModuleConfig{Enabled: cloneBool(m.Firewall.Enabled)}
	}
	if m.Logging != nil {
		result["logging"] = ModuleConfig{}
	}
	if m.TailnetRouter != nil {
		result["tailnet-router"] = ModuleConfig{Enabled: cloneBool(m.TailnetRouter.Enabled)}
	}
	if m.LiteLLM != nil {
		result["litellm"] = ModuleConfig{Enabled: cloneBool(m.LiteLLM.Enabled), Upstreams: cloneLiteLLMUpstreams(m.LiteLLM.Upstreams), Models: cloneLiteLLMModels(m.LiteLLM.Models)}
	}
	if m.Printer != nil {
		result["printer"] = ModuleConfig{Enabled: cloneBool(m.Printer.Enabled)}
	}
	if m.AIOps != nil {
		result["aiops"] = ModuleConfig{Enabled: cloneBool(m.AIOps.Enabled), ModelAlias: m.AIOps.ModelAlias}
	}
	if m.Gatus != nil {
		result["gatus"] = ModuleConfig{Enabled: cloneBool(m.Gatus.Enabled)}
	}
	return result
}

func ModulesConfigFromMap(input map[string]ModuleConfig) ModulesConfig {
	var result ModulesConfig
	if _, ok := input["dns"]; ok {
		result.DNS = &DNSModuleConfig{}
	}
	if config, ok := input["monitoring"]; ok {
		result.Monitoring = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	if config, ok := input["firewall"]; ok {
		result.Firewall = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	if _, ok := input["logging"]; ok {
		result.Logging = &MandatoryModuleConfig{}
	}
	if config, ok := input["tailnet-router"]; ok {
		result.TailnetRouter = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	if config, ok := input["litellm"]; ok {
		result.LiteLLM = &LiteLLMModuleConfig{Enabled: cloneBool(config.Enabled), Upstreams: cloneLiteLLMUpstreams(config.Upstreams), Models: cloneLiteLLMModels(config.Models)}
	}
	if config, ok := input["printer"]; ok {
		result.Printer = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	if config, ok := input["aiops"]; ok {
		result.AIOps = &AIOpsModuleConfig{Enabled: cloneBool(config.Enabled), ModelAlias: config.ModelAlias}
	}
	if config, ok := input["gatus"]; ok {
		result.Gatus = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	return result
}

func (m *ModulesConfig) Set(name string, config ModuleConfig) error {
	switch name {
	case "dns":
		if config.Enabled != nil {
			return errors.New("modules.dns.enabled: mandatory module cannot be disabled")
		}
		m.DNS = &DNSModuleConfig{}
	case "monitoring":
		m.Monitoring = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	case "firewall":
		m.Firewall = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	case "logging":
		if config.Enabled != nil {
			return errors.New("modules.logging.enabled: mandatory module cannot be disabled")
		}
		m.Logging = &MandatoryModuleConfig{}
	case "tailnet-router":
		m.TailnetRouter = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	case "litellm":
		upstreams := config.Upstreams
		models := config.Models
		if len(upstreams) == 0 && len(models) == 0 && m.LiteLLM != nil {
			upstreams = m.LiteLLM.Upstreams
			models = m.LiteLLM.Models
		}
		m.LiteLLM = &LiteLLMModuleConfig{Enabled: cloneBool(config.Enabled), Upstreams: cloneLiteLLMUpstreams(upstreams), Models: cloneLiteLLMModels(models)}
	case "printer":
		m.Printer = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	case "aiops":
		alias := config.ModelAlias
		if alias == "" && m.AIOps != nil {
			alias = m.AIOps.ModelAlias
		}
		m.AIOps = &AIOpsModuleConfig{Enabled: cloneBool(config.Enabled), ModelAlias: alias}
	case "gatus":
		m.Gatus = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	default:
		return fmt.Errorf("modules.%s: unknown first-party module", name)
	}
	return nil
}

func cloneBool(value *bool) *bool {
	if value == nil {
		return nil
	}
	copy := *value
	return &copy
}

func cloneLiteLLMUpstreams(values []LiteLLMUpstreamConfig) []LiteLLMUpstreamConfig {
	return append([]LiteLLMUpstreamConfig(nil), values...)
}

func cloneLiteLLMModels(values []LiteLLMModelConfig) []LiteLLMModelConfig {
	return append([]LiteLLMModelConfig(nil), values...)
}

func ValidateLiteLLMConfig(config ModuleConfig) error {
	if len(config.Upstreams) == 0 {
		return errors.New("modules.litellm.upstreams must contain at least one upstream")
	}
	if len(config.Upstreams) > 16 {
		return errors.New("modules.litellm.upstreams must contain at most 16 upstreams")
	}
	if len(config.Models) == 0 {
		return errors.New("modules.litellm.models must contain at least one explicit model alias")
	}
	if len(config.Models) > 32 {
		return errors.New("modules.litellm.models must contain at most 32 model aliases")
	}
	upstreams := make(map[string]struct{}, len(config.Upstreams))
	secretReferences := make(map[string]string, len(config.Upstreams))
	for _, upstream := range config.Upstreams {
		if !modelTokenPattern.MatchString(upstream.Name) {
			return fmt.Errorf("modules.litellm.upstreams.name %q is not a safe token", upstream.Name)
		}
		if _, exists := upstreams[upstream.Name]; exists {
			return fmt.Errorf("modules.litellm has duplicate upstream %q", upstream.Name)
		}
		upstreams[upstream.Name] = struct{}{}
		parsed, err := url.Parse(upstream.BaseURL)
		if err != nil || parsed.Scheme != "https" || parsed.Host == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
			return fmt.Errorf("modules.litellm upstream %s requires a valid HTTPS base_url", upstream.Name)
		}
		if !liteLLMSecretReferencePattern.MatchString(upstream.APIKeySecret) {
			return fmt.Errorf("modules.litellm upstream %s has an invalid api_key_secret reference", upstream.Name)
		}
		secretID := LiteLLMSecretReferenceID(upstream.APIKeySecret)
		if previous, exists := secretReferences[secretID]; exists && previous != upstream.APIKeySecret {
			return fmt.Errorf("modules.litellm upstreams %q and %q have colliding api_key_secret references", previous, upstream.APIKeySecret)
		}
		secretReferences[secretID] = upstream.APIKeySecret
	}
	aliases := make(map[string]struct{}, len(config.Models))
	for _, model := range config.Models {
		if !modelTokenPattern.MatchString(model.Alias) {
			return fmt.Errorf("modules.litellm model alias %q is not a safe token", model.Alias)
		}
		if _, exists := aliases[model.Alias]; exists {
			return fmt.Errorf("modules.litellm has duplicate model alias %q", model.Alias)
		}
		aliases[model.Alias] = struct{}{}
		if _, exists := upstreams[model.Upstream]; !exists {
			return fmt.Errorf("modules.litellm model alias %s references unknown upstream %q", model.Alias, model.Upstream)
		}
		if !providerModelPattern.MatchString(model.Model) {
			return fmt.Errorf("modules.litellm model %s has an invalid provider model identifier", model.Alias)
		}
	}
	return nil
}

// ResolveLiteLLMAlias is the provider-neutral client contract. Callers may
// use only an explicitly declared alias; provider model identifiers are
// internal mapping data and are never accepted as implicit public models.
func ResolveLiteLLMAlias(config ModuleConfig, alias string) (LiteLLMModelConfig, error) {
	if err := ValidateLiteLLMConfig(config); err != nil {
		return LiteLLMModelConfig{}, err
	}
	for _, model := range config.Models {
		if model.Alias == alias {
			return model, nil
		}
	}
	return LiteLLMModelConfig{}, fmt.Errorf("undeclared LiteLLM model alias %q", alias)
}

func ConfigFromSite(s Site) SiteConfig {
	return SiteConfig{
		APIVersion: s.APIVersion, PlatformVersion: s.PlatformVersion,
		SchemaVersion: s.SchemaVersion, StorageProfile: s.StorageProfile,
		StorageDevice: s.StorageDevice, Gateway: Gateway{Mode: s.Gateway.Mode, Upstream: s.Gateway.Upstream, Publish: append([]GatewayPublication(nil), s.Gateway.Publish...)},
		BootstrapAddress: s.BootstrapAddress,
		SSHIdentityFile:  s.SSHIdentityFile, PhysicalNetwork: s.PhysicalNetwork,
		TestedVersions: s.TestedVersions, Network: s.Network, PKI: s.PKI,
		SecretMetadata: s.SecretMetadata, Ownership: s.Ownership,
		Modules: ModulesConfigFromMap(s.ModuleConfig), DHCPReservations: append([]DHCPReservation(nil), s.DHCPReservations...),
		USBExports:        append([]USBExportBinding(nil), s.USBExports...),
		DNSRecords:        append([]UserDNSRecord(nil), s.DNSRecords...),
		UserFirewallRules: append([]UserFirewallRule(nil), s.UserFirewallRules...),
	}
}

func (c SiteConfig) BaseSite() Site {
	mode := c.Gateway.Mode
	if mode == "" {
		mode = GatewayModeManaged
	}
	s := NewSite(c.SecretMetadata.InstallationID, c.SecretMetadata.AgeRecipient, mode)
	if c.Gateway.Upstream.Mode != "" {
		s.Gateway.Upstream.Mode = c.Gateway.Upstream.Mode
	}
	if c.Gateway.Upstream.MAC != "" {
		s.Gateway.Upstream.MAC = c.Gateway.Upstream.MAC
	}
	if len(c.Gateway.Publish) > 0 {
		s.Gateway.Publish = append([]GatewayPublication(nil), c.Gateway.Publish...)
	}
	if c.APIVersion != "" {
		s.APIVersion = c.APIVersion
	}
	if c.PlatformVersion != "" {
		s.PlatformVersion = c.PlatformVersion
	}
	if c.SchemaVersion != 0 {
		s.SchemaVersion = c.SchemaVersion
	}
	if c.StorageProfile != "" {
		s.StorageProfile = c.StorageProfile
	}
	if c.StorageDevice != "" {
		s.StorageDevice = c.StorageDevice
	}
	if c.BootstrapAddress != "" {
		s.BootstrapAddress = c.BootstrapAddress
	}
	if c.SSHIdentityFile != "" {
		s.SSHIdentityFile = c.SSHIdentityFile
	}
	if c.PhysicalNetwork.Mode != "" {
		s.PhysicalNetwork = c.PhysicalNetwork
	}
	if c.TestedVersions.Gateway != "" {
		s.TestedVersions.Gateway = c.TestedVersions.Gateway
	}
	if c.TestedVersions.Pulse != "" {
		s.TestedVersions.Pulse = c.TestedVersions.Pulse
	}
	if c.Network.Domain != "" {
		s.Network.Domain = c.Network.Domain
	}
	if len(c.Network.Zones) > 0 {
		s.Network.Zones = append([]Zone(nil), c.Network.Zones...)
		for index := range s.Network.Zones {
			// Keep existing v3 site files without the semantic field readable;
			// the fixed v3 names make this inference unambiguous. New rendered
			// configuration always includes the explicit type.
			if s.Network.Zones[index].Type == "" {
				s.Network.Zones[index].Type = zoneTypeForName(s.Network.Zones[index].Name)
			}
		}
	}
	if c.PKI.RootCommonName != "" {
		s.PKI.RootCommonName = c.PKI.RootCommonName
	}
	if c.PKI.RootFingerprint != "" {
		s.PKI.RootFingerprint = c.PKI.RootFingerprint
	}
	if c.PKI.RootExpiry != "" {
		s.PKI.RootExpiry = c.PKI.RootExpiry
	}
	if c.PKI.IssuingCommonName != "" {
		s.PKI.IssuingCommonName = c.PKI.IssuingCommonName
	}
	if c.PKI.IssuingFingerprint != "" {
		s.PKI.IssuingFingerprint = c.PKI.IssuingFingerprint
	}
	if c.PKI.IssuingExpiry != "" {
		s.PKI.IssuingExpiry = c.PKI.IssuingExpiry
	}
	if c.SecretMetadata.InstallationID != "" {
		s.SecretMetadata.InstallationID = c.SecretMetadata.InstallationID
	}
	if c.SecretMetadata.AgeRecipient != "" {
		s.SecretMetadata.AgeRecipient = c.SecretMetadata.AgeRecipient
	}
	if c.Ownership.PlatformGuestIDMin != 0 {
		s.Ownership.PlatformGuestIDMin = c.Ownership.PlatformGuestIDMin
	}
	if c.Ownership.PlatformGuestIDMax != 0 {
		s.Ownership.PlatformGuestIDMax = c.Ownership.PlatformGuestIDMax
	}
	if c.Ownership.ModuleGuestIDMin != 0 {
		s.Ownership.ModuleGuestIDMin = c.Ownership.ModuleGuestIDMin
	}
	if c.Ownership.ModuleGuestIDMax != 0 {
		s.Ownership.ModuleGuestIDMax = c.Ownership.ModuleGuestIDMax
	}
	if c.Ownership.UserGuestIDMin != 0 {
		s.Ownership.UserGuestIDMin = c.Ownership.UserGuestIDMin
	}
	if c.Ownership.UserGuestIDMax != 0 {
		s.Ownership.UserGuestIDMax = c.Ownership.UserGuestIDMax
	}
	s.Ownership.UserWorkloadsManaged = c.Ownership.UserWorkloadsManaged
	s.DHCPReservations = append([]DHCPReservation(nil), c.DHCPReservations...)
	s.DNSRecords = append([]UserDNSRecord(nil), c.DNSRecords...)
	s.UserFirewallRules = append([]UserFirewallRule(nil), c.UserFirewallRules...)
	s.USBExports = append([]USBExportBinding(nil), c.USBExports...)
	s.ModuleConfig = c.Modules.Map()
	return s
}

func (c SiteConfig) Validate() error {
	return c.BaseSite().Validate()
}

func cloneModuleConfig(input map[string]ModuleConfig) map[string]ModuleConfig {
	if len(input) == 0 {
		return nil
	}
	output := make(map[string]ModuleConfig, len(input))
	for name, config := range input {
		output[name] = ModuleConfig{Enabled: cloneBool(config.Enabled), ModelAlias: config.ModelAlias, Upstreams: cloneLiteLLMUpstreams(config.Upstreams), Models: cloneLiteLLMModels(config.Models)}
	}
	return output
}
