package model

import (
	"errors"
	"fmt"
	"net/url"
)

// SiteConfig is the concise operator-authored v0.3 configuration. Expanded
// components and resolved module state are generated by the composition layer
// and are deliberately not accepted from site.yml.
type SiteConfig struct {
	APIVersion       string             `yaml:"api_version" json:"api_version" jsonschema:"const=boetticher/v3"`
	PlatformVersion  string             `yaml:"platform_version" json:"platform_version,omitempty" jsonschema:"const=0.3.34"`
	SchemaVersion    int                `yaml:"schema_version" json:"schema_version,omitempty" jsonschema:"const=3"`
	StorageProfile   string             `yaml:"storage_profile" json:"storage_profile,omitempty" jsonschema:"enum=single-disk,enum=dedicated-data-disk"`
	StorageDevice    string             `yaml:"storage_device,omitempty" json:"storage_device,omitempty"`
	Gateway          Gateway            `yaml:"gateway" json:"gateway,omitempty"`
	BootstrapAddress string             `yaml:"bootstrap_address,omitempty" json:"bootstrap_address,omitempty"`
	SSHIdentityFile  string             `yaml:"ssh_identity_file,omitempty" json:"ssh_identity_file,omitempty"`
	PhysicalNetwork  PhysicalNetwork    `yaml:"physical_network" json:"physical_network,omitempty"`
	TestedVersions   TestedVersions     `yaml:"tested_versions" json:"tested_versions,omitempty"`
	Network          Network            `yaml:"network" json:"network,omitempty"`
	PKI              PKIMetadata        `yaml:"pki" json:"pki,omitempty"`
	SecretMetadata   SecretMetadata     `yaml:"secret_metadata" json:"secret_metadata,omitempty"`
	Ownership        OwnershipPolicy    `yaml:"ownership" json:"ownership,omitempty"`
	Modules          ModulesConfig      `yaml:"modules,omitempty" json:"modules,omitempty"`
	USBExports       []USBExportBinding `yaml:"usb_exports,omitempty" json:"usb_exports,omitempty"`
	DHCPReservations []DHCPReservation  `yaml:"dhcp_reservations,omitempty" json:"dhcp_reservations,omitempty"`
	DNSRecords       []UserDNSRecord    `yaml:"dns_records,omitempty" json:"dns_records,omitempty"`
}

// ModulesConfig is the authoritative operator-facing module configuration.
// Each built-in module owns a typed configuration shape; the resolved Site
// keeps a small internal projection for providers that only need lookup by
// module name.
type ModulesConfig struct {
	DNS           *DNSModuleConfig        `yaml:"dns,omitempty" json:"dns,omitempty"`
	Monitoring    *ToggleModuleConfig     `yaml:"monitoring,omitempty" json:"monitoring,omitempty"`
	Firewall      *ToggleModuleConfig     `yaml:"firewall,omitempty" json:"firewall,omitempty"`
	Logging       *MandatoryModuleConfig  `yaml:"logging,omitempty" json:"logging,omitempty"`
	TailnetRouter *ToggleModuleConfig     `yaml:"tailnet-router,omitempty" json:"tailnet-router,omitempty"`
	LiteLLM       *LiteLLMModuleConfig    `yaml:"litellm,omitempty" json:"litellm,omitempty"`
	StreamDeck    *StreamDeckModuleConfig `yaml:"streamdeck,omitempty" json:"streamdeck,omitempty"`
}

type DNSModuleConfig struct {
	Provider DNSProvider `yaml:"provider,omitempty" json:"provider,omitempty" jsonschema:"enum=blocky,enum=adguard,default=blocky"`
}

// MandatoryModuleConfig intentionally has no enable field. Its empty typed
// shape makes modules.logging: {} valid while strict decoding rejects any
// operator attempt to persist lifecycle state for a mandatory module.
type MandatoryModuleConfig struct{}

type ToggleModuleConfig struct {
	Enabled *bool `yaml:"enabled,omitempty" json:"enabled,omitempty"`
}

type LiteLLMModuleConfig struct {
	Enabled   *bool                   `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Upstreams []LiteLLMUpstreamConfig `yaml:"upstreams,omitempty" json:"upstreams,omitempty"`
	Models    []LiteLLMModelConfig    `yaml:"models,omitempty" json:"models,omitempty"`
}

type StreamDeckModuleConfig struct {
	Enabled                *bool    `yaml:"enabled,omitempty" json:"enabled,omitempty"`
	Brightness             int      `yaml:"brightness,omitempty" json:"brightness,omitempty" jsonschema:"minimum=1,maximum=100,default=40"`
	RefreshSeconds         int      `yaml:"refresh_seconds,omitempty" json:"refresh_seconds,omitempty" jsonschema:"minimum=1,maximum=300,default=5"`
	RequestTimeoutSeconds  int      `yaml:"request_timeout_seconds,omitempty" json:"request_timeout_seconds,omitempty" jsonschema:"minimum=1,maximum=30,default=3"`
	DefaultPage            string   `yaml:"default_page,omitempty" json:"default_page,omitempty" jsonschema:"enum=overview,enum=guests,default=overview"`
	PinnedGuests           []string `yaml:"pinned_guests,omitempty" json:"pinned_guests,omitempty"`
	StorageWarningPercent  int      `yaml:"storage_warning_percent,omitempty" json:"storage_warning_percent,omitempty" jsonschema:"minimum=1,maximum=99,default=80"`
	StorageCriticalPercent int      `yaml:"storage_critical_percent,omitempty" json:"storage_critical_percent,omitempty" jsonschema:"minimum=2,maximum=100,default=90"`
}

type LiteLLMUpstreamConfig struct {
	Name         string `yaml:"name" json:"name"`
	BaseURL      string `yaml:"base_url" json:"base_url"`
	APIKeySecret string `yaml:"api_key_secret" json:"api_key_secret"`
}

type LiteLLMModelConfig struct {
	Alias    string `yaml:"alias" json:"alias"`
	Upstream string `yaml:"upstream" json:"upstream"`
	Model    string `yaml:"model" json:"model"`
}

// Map returns the normalized internal lookup projection. It is deliberately
// not used as the persisted SiteConfig representation.
func (m ModulesConfig) Map() map[string]ModuleConfig {
	result := make(map[string]ModuleConfig)
	if m.DNS != nil {
		result["dns"] = ModuleConfig{Provider: string(m.DNS.Provider)}
	}
	if m.Monitoring != nil {
		result["monitoring"] = ModuleConfig{Enabled: cloneBool(m.Monitoring.Enabled)}
	}
	if m.Firewall != nil {
		result["firewall"] = ModuleConfig{Enabled: cloneBool(m.Firewall.Enabled)}
	}
	if m.Logging != nil {
		result["logging"] = ModuleConfig{}
	}
	if m.TailnetRouter != nil {
		result["tailnet-router"] = ModuleConfig{Enabled: cloneBool(m.TailnetRouter.Enabled)}
	}
	if m.LiteLLM != nil {
		result["litellm"] = ModuleConfig{Enabled: cloneBool(m.LiteLLM.Enabled), Upstreams: cloneLiteLLMUpstreams(m.LiteLLM.Upstreams), Models: cloneLiteLLMModels(m.LiteLLM.Models)}
	}
	if m.StreamDeck != nil {
		c := normalizedStreamDeckConfig(*m.StreamDeck)
		result["streamdeck"] = ModuleConfig{Enabled: cloneBool(c.Enabled), Brightness: c.Brightness, RefreshSeconds: c.RefreshSeconds, RequestTimeoutSeconds: c.RequestTimeoutSeconds, DefaultPage: c.DefaultPage, PinnedGuests: append([]string(nil), c.PinnedGuests...), StorageWarningPercent: c.StorageWarningPercent, StorageCriticalPercent: c.StorageCriticalPercent}
	}
	return result
}

func ModulesConfigFromMap(input map[string]ModuleConfig) ModulesConfig {
	var result ModulesConfig
	if config, ok := input["dns"]; ok {
		result.DNS = &DNSModuleConfig{Provider: DNSProvider(config.Provider)}
	}
	if config, ok := input["monitoring"]; ok {
		result.Monitoring = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	if config, ok := input["firewall"]; ok {
		result.Firewall = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	if _, ok := input["logging"]; ok {
		result.Logging = &MandatoryModuleConfig{}
	}
	if config, ok := input["tailnet-router"]; ok {
		result.TailnetRouter = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	}
	if config, ok := input["litellm"]; ok {
		result.LiteLLM = &LiteLLMModuleConfig{Enabled: cloneBool(config.Enabled), Upstreams: cloneLiteLLMUpstreams(config.Upstreams), Models: cloneLiteLLMModels(config.Models)}
	}
	if config, ok := input["streamdeck"]; ok {
		result.StreamDeck = &StreamDeckModuleConfig{Enabled: cloneBool(config.Enabled), Brightness: config.Brightness, RefreshSeconds: config.RefreshSeconds, RequestTimeoutSeconds: config.RequestTimeoutSeconds, DefaultPage: config.DefaultPage, PinnedGuests: append([]string(nil), config.PinnedGuests...), StorageWarningPercent: config.StorageWarningPercent, StorageCriticalPercent: config.StorageCriticalPercent}
	}
	return result
}

func (m *ModulesConfig) Set(name string, config ModuleConfig) error {
	switch name {
	case "dns":
		if config.Enabled != nil {
			return errors.New("modules.dns.enabled: mandatory module cannot be disabled")
		}
		m.DNS = &DNSModuleConfig{Provider: DNSProvider(config.Provider)}
	case "monitoring":
		m.Monitoring = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	case "firewall":
		m.Firewall = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	case "logging":
		if config.Enabled != nil {
			return errors.New("modules.logging.enabled: mandatory module cannot be disabled")
		}
		m.Logging = &MandatoryModuleConfig{}
	case "tailnet-router":
		m.TailnetRouter = &ToggleModuleConfig{Enabled: cloneBool(config.Enabled)}
	case "litellm":
		upstreams := config.Upstreams
		models := config.Models
		if len(upstreams) == 0 && len(models) == 0 && m.LiteLLM != nil {
			upstreams = m.LiteLLM.Upstreams
			models = m.LiteLLM.Models
		}
		m.LiteLLM = &LiteLLMModuleConfig{Enabled: cloneBool(config.Enabled), Upstreams: cloneLiteLLMUpstreams(upstreams), Models: cloneLiteLLMModels(models)}
	case "streamdeck":
		current := StreamDeckModuleConfig{}
		if m.StreamDeck != nil {
			current = *m.StreamDeck
		}
		if config.Brightness != 0 {
			current.Brightness = config.Brightness
		}
		if config.RefreshSeconds != 0 {
			current.RefreshSeconds = config.RefreshSeconds
		}
		if config.RequestTimeoutSeconds != 0 {
			current.RequestTimeoutSeconds = config.RequestTimeoutSeconds
		}
		if config.DefaultPage != "" {
			current.DefaultPage = config.DefaultPage
		}
		if config.PinnedGuests != nil {
			current.PinnedGuests = append([]string(nil), config.PinnedGuests...)
		}
		if config.StorageWarningPercent != 0 {
			current.StorageWarningPercent = config.StorageWarningPercent
		}
		if config.StorageCriticalPercent != 0 {
			current.StorageCriticalPercent = config.StorageCriticalPercent
		}
		current.Enabled = cloneBool(config.Enabled)
		m.StreamDeck = &current
	default:
		return fmt.Errorf("modules.%s: unknown first-party module", name)
	}
	return nil
}

func normalizedStreamDeckConfig(c StreamDeckModuleConfig) StreamDeckModuleConfig {
	if c.Brightness == 0 {
		c.Brightness = 40
	}
	if c.RefreshSeconds == 0 {
		c.RefreshSeconds = 5
	}
	if c.RequestTimeoutSeconds == 0 {
		c.RequestTimeoutSeconds = 3
	}
	if c.DefaultPage == "" {
		c.DefaultPage = "overview"
	}
	if c.StorageWarningPercent == 0 {
		c.StorageWarningPercent = 80
	}
	if c.StorageCriticalPercent == 0 {
		c.StorageCriticalPercent = 90
	}
	return c
}

func ValidateStreamDeckConfig(c ModuleConfig) error {
	if c.Brightness < 1 || c.Brightness > 100 {
		return errors.New("modules.streamdeck.brightness must be between 1 and 100")
	}
	if c.RefreshSeconds < 1 || c.RefreshSeconds > 300 {
		return errors.New("modules.streamdeck.refresh_seconds must be between 1 and 300")
	}
	if c.RequestTimeoutSeconds < 1 || c.RequestTimeoutSeconds > 30 {
		return errors.New("modules.streamdeck.request_timeout_seconds must be between 1 and 30")
	}
	if c.DefaultPage != "overview" && c.DefaultPage != "guests" {
		return errors.New("modules.streamdeck.default_page must be overview or guests")
	}
	if c.StorageWarningPercent < 1 || c.StorageWarningPercent > 99 || c.StorageCriticalPercent < 2 || c.StorageCriticalPercent > 100 || c.StorageWarningPercent >= c.StorageCriticalPercent {
		return errors.New("modules.streamdeck storage thresholds must be ordered percentages")
	}
	seen := map[string]bool{}
	for _, guest := range c.PinnedGuests {
		if !modelTokenPattern.MatchString(guest) {
			return fmt.Errorf("modules.streamdeck.pinned_guests contains unsafe guest %q", guest)
		}
		if seen[guest] {
			return fmt.Errorf("modules.streamdeck.pinned_guests contains duplicate %q", guest)
		}
		seen[guest] = true
	}
	return nil
}

func cloneBool(value *bool) *bool {
	if value == nil {
		return nil
	}
	copy := *value
	return &copy
}

func cloneLiteLLMUpstreams(values []LiteLLMUpstreamConfig) []LiteLLMUpstreamConfig {
	return append([]LiteLLMUpstreamConfig(nil), values...)
}

func cloneLiteLLMModels(values []LiteLLMModelConfig) []LiteLLMModelConfig {
	return append([]LiteLLMModelConfig(nil), values...)
}

func ValidateLiteLLMConfig(config ModuleConfig) error {
	if len(config.Upstreams) == 0 {
		return errors.New("modules.litellm.upstreams must contain at least one upstream")
	}
	if len(config.Models) == 0 {
		return errors.New("modules.litellm.models must contain at least one explicit model alias")
	}
	upstreams := make(map[string]struct{}, len(config.Upstreams))
	for _, upstream := range config.Upstreams {
		if !modelTokenPattern.MatchString(upstream.Name) {
			return fmt.Errorf("modules.litellm.upstreams.name %q is not a safe token", upstream.Name)
		}
		if _, exists := upstreams[upstream.Name]; exists {
			return fmt.Errorf("modules.litellm has duplicate upstream %q", upstream.Name)
		}
		upstreams[upstream.Name] = struct{}{}
		parsed, err := url.Parse(upstream.BaseURL)
		if err != nil || parsed.Scheme != "https" || parsed.Host == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
			return fmt.Errorf("modules.litellm upstream %s requires a valid HTTPS base_url", upstream.Name)
		}
		if !secretReferencePattern.MatchString(upstream.APIKeySecret) {
			return fmt.Errorf("modules.litellm upstream %s has an invalid api_key_secret reference", upstream.Name)
		}
	}
	aliases := make(map[string]struct{}, len(config.Models))
	for _, model := range config.Models {
		if !modelTokenPattern.MatchString(model.Alias) {
			return fmt.Errorf("modules.litellm model alias %q is not a safe token", model.Alias)
		}
		if _, exists := aliases[model.Alias]; exists {
			return fmt.Errorf("modules.litellm has duplicate model alias %q", model.Alias)
		}
		aliases[model.Alias] = struct{}{}
		if _, exists := upstreams[model.Upstream]; !exists {
			return fmt.Errorf("modules.litellm model alias %s references unknown upstream %q", model.Alias, model.Upstream)
		}
		if !providerModelPattern.MatchString(model.Model) {
			return fmt.Errorf("modules.litellm model %s has an invalid provider model identifier", model.Alias)
		}
	}
	return nil
}

// ResolveLiteLLMAlias is the provider-neutral client contract. Callers may
// use only an explicitly declared alias; provider model identifiers are
// internal mapping data and are never accepted as implicit public models.
func ResolveLiteLLMAlias(config ModuleConfig, alias string) (LiteLLMModelConfig, error) {
	if err := ValidateLiteLLMConfig(config); err != nil {
		return LiteLLMModelConfig{}, err
	}
	for _, model := range config.Models {
		if model.Alias == alias {
			return model, nil
		}
	}
	return LiteLLMModelConfig{}, fmt.Errorf("undeclared LiteLLM model alias %q", alias)
}

func ConfigFromSite(s Site) SiteConfig {
	return SiteConfig{
		APIVersion: s.APIVersion, PlatformVersion: s.PlatformVersion,
		SchemaVersion: s.SchemaVersion, StorageProfile: s.StorageProfile,
		StorageDevice: s.StorageDevice, Gateway: s.Gateway,
		BootstrapAddress: s.BootstrapAddress,
		SSHIdentityFile:  s.SSHIdentityFile, PhysicalNetwork: s.PhysicalNetwork,
		TestedVersions: s.TestedVersions, Network: s.Network, PKI: s.PKI,
		SecretMetadata: s.SecretMetadata, Ownership: s.Ownership,
		Modules: ModulesConfigFromMap(s.ModuleConfig), DHCPReservations: append([]DHCPReservation(nil), s.DHCPReservations...),
		USBExports: append([]USBExportBinding(nil), s.USBExports...),
		DNSRecords: append([]UserDNSRecord(nil), s.DNSRecords...),
	}
}

func (c SiteConfig) BaseSite() Site {
	mode := c.Gateway.Mode
	if mode == "" {
		mode = GatewayModeManaged
	}
	s := NewSite(c.SecretMetadata.InstallationID, c.SecretMetadata.AgeRecipient, mode)
	if c.APIVersion != "" {
		s.APIVersion = c.APIVersion
	}
	if c.PlatformVersion != "" {
		s.PlatformVersion = c.PlatformVersion
	}
	if c.SchemaVersion != 0 {
		s.SchemaVersion = c.SchemaVersion
	}
	if c.StorageProfile != "" {
		s.StorageProfile = c.StorageProfile
	}
	if c.StorageDevice != "" {
		s.StorageDevice = c.StorageDevice
	}
	if c.BootstrapAddress != "" {
		s.BootstrapAddress = c.BootstrapAddress
	}
	if c.SSHIdentityFile != "" {
		s.SSHIdentityFile = c.SSHIdentityFile
	}
	if c.PhysicalNetwork.Mode != "" {
		s.PhysicalNetwork = c.PhysicalNetwork
	}
	if c.TestedVersions.Gateway != "" {
		s.TestedVersions.Gateway = c.TestedVersions.Gateway
	}
	if c.TestedVersions.Pulse != "" {
		s.TestedVersions.Pulse = c.TestedVersions.Pulse
	}
	if c.Network.Domain != "" {
		s.Network.Domain = c.Network.Domain
	}
	if len(c.Network.Zones) > 0 {
		s.Network.Zones = append([]Zone(nil), c.Network.Zones...)
		for index := range s.Network.Zones {
			// Keep existing v3 site files without the semantic field readable;
			// the fixed V1 names make this inference unambiguous. New rendered
			// configuration always includes the explicit type.
			if s.Network.Zones[index].Type == "" {
				s.Network.Zones[index].Type = zoneTypeForName(s.Network.Zones[index].Name)
			}
		}
	}
	if c.PKI.RootCommonName != "" {
		s.PKI.RootCommonName = c.PKI.RootCommonName
	}
	if c.PKI.RootFingerprint != "" {
		s.PKI.RootFingerprint = c.PKI.RootFingerprint
	}
	if c.PKI.RootExpiry != "" {
		s.PKI.RootExpiry = c.PKI.RootExpiry
	}
	if c.PKI.IssuingCommonName != "" {
		s.PKI.IssuingCommonName = c.PKI.IssuingCommonName
	}
	if c.PKI.IssuingFingerprint != "" {
		s.PKI.IssuingFingerprint = c.PKI.IssuingFingerprint
	}
	if c.PKI.IssuingExpiry != "" {
		s.PKI.IssuingExpiry = c.PKI.IssuingExpiry
	}
	if c.SecretMetadata.InstallationID != "" {
		s.SecretMetadata.InstallationID = c.SecretMetadata.InstallationID
	}
	if c.SecretMetadata.AgeRecipient != "" {
		s.SecretMetadata.AgeRecipient = c.SecretMetadata.AgeRecipient
	}
	if c.Ownership.PlatformGuestIDMin != 0 {
		s.Ownership.PlatformGuestIDMin = c.Ownership.PlatformGuestIDMin
	}
	if c.Ownership.PlatformGuestIDMax != 0 {
		s.Ownership.PlatformGuestIDMax = c.Ownership.PlatformGuestIDMax
	}
	if c.Ownership.ModuleGuestIDMin != 0 {
		s.Ownership.ModuleGuestIDMin = c.Ownership.ModuleGuestIDMin
	}
	if c.Ownership.ModuleGuestIDMax != 0 {
		s.Ownership.ModuleGuestIDMax = c.Ownership.ModuleGuestIDMax
	}
	if c.Ownership.UserGuestIDMin != 0 {
		s.Ownership.UserGuestIDMin = c.Ownership.UserGuestIDMin
	}
	if c.Ownership.UserGuestIDMax != 0 {
		s.Ownership.UserGuestIDMax = c.Ownership.UserGuestIDMax
	}
	s.Ownership.UserWorkloadsManaged = c.Ownership.UserWorkloadsManaged
	s.DHCPReservations = append([]DHCPReservation(nil), c.DHCPReservations...)
	s.DNSRecords = append([]UserDNSRecord(nil), c.DNSRecords...)
	s.USBExports = append([]USBExportBinding(nil), c.USBExports...)
	s.ModuleConfig = c.Modules.Map()
	return s
}

func (c SiteConfig) Validate() error {
	return c.BaseSite().Validate()
}

func cloneModuleConfig(input map[string]ModuleConfig) map[string]ModuleConfig {
	if len(input) == 0 {
		return nil
	}
	output := make(map[string]ModuleConfig, len(input))
	for name, config := range input {
		output[name] = ModuleConfig{Enabled: cloneBool(config.Enabled), Provider: config.Provider, Upstreams: cloneLiteLLMUpstreams(config.Upstreams), Models: cloneLiteLLMModels(config.Models), Brightness: config.Brightness, RefreshSeconds: config.RefreshSeconds, RequestTimeoutSeconds: config.RequestTimeoutSeconds, DefaultPage: config.DefaultPage, PinnedGuests: append([]string(nil), config.PinnedGuests...), StorageWarningPercent: config.StorageWarningPercent, StorageCriticalPercent: config.StorageCriticalPercent}
	}
	return output
}
