package cli

import "strings"

// commandSpec is the single source for the public command menu printed by the
// CLI and published on the docs site.
type commandSpec struct {
	Usage string
}

type helpSpec struct {
	Usage     string
	Purpose   string
	Arguments string
	Options   string
	Safety    string
	Examples  string
	Related   string
}

var commandSpecs = []commandSpec{
	{Usage: "boetticher controller bootstrap|status|reboot [--operator USER] [--confirm-key-login] [--yes]"},
	{Usage: "boetticher host create-identity|show-public-key|import-host-key|enroll|apply|status|plan-storage|teardown|reboot ..."},
	{Usage: "boetticher host register-system|list-systems|system-status|unregister-system ..."},
	{Usage: "boetticher module <capability> <action> [flags]"},
	{Usage: "boetticher module firewall plan|apply|status|reboot|test|teardown [flags]"},
	{Usage: "boetticher module dns plan|apply|status|teardown|test|add-record|remove-record|list-records [flags]"},
	{Usage: "boetticher module dhcp plan|apply|status|teardown|test|add-reservation|remove-reservation|list-reservations|list-leases [flags]"},
	{Usage: "boetticher module observability plan|apply|status|test|teardown|secrets [--yes] [--public-domain DOMAIN] [--holmes-model MODEL]"},
	{Usage: "boetticher module observability alerts pushover apply|status|test|remove [flags]"},
	{Usage: "boetticher module logging query|status [flags]"},
	{Usage: "boetticher module aiops ask QUESTION [--yes] [--json]"},
	{Usage: "boetticher module vpn plan|apply|status|teardown|add-client|remove-client [--location SELECTOR] [flags]"},
	{Usage: "boetticher module tailnet plan|apply|status|test|teardown [flags]"},
	{Usage: "boetticher module media plan|apply|status|test|teardown [--plan|--yes] [--cloudflare-token-file FILE]"},
}

var advancedCommandSpecs = []commandSpec{
	{Usage: "boetticher host status --details"},
	{Usage: "boetticher host plan-storage"},
	{Usage: "boetticher module <capability> <action> [--yes]"},
}

// helpSpecs is keyed by the command path before -h/--help. Keeping nested
// paths explicit makes every help request useful without making command
// dispatch depend on a second parser or on a recursive help hint.
var helpSpecs = map[string]helpSpec{
	"host register-system":                 {Usage: "boetticher host register-system NAME --vmid VMID --address IPv4 --port PORT [--check] [--plan|--yes]", Purpose: "Register an existing VM or LXC and reconcile its bounded SERVERS network policy.", Arguments: "NAME identifies one existing guest; VMID, address, and port are required.", Options: "--check enables one bounded TCP monitoring check; --plan previews without mutation; --yes approves save and provider reconciliation.", Safety: "The guest is never created, deleted, started, stopped, or reconfigured. The exact vmbr1 VLAN 20 identity must be proven first.", Examples: "boetticher host register-system existing-system --vmid 501 --address 10.10.20.61 --port 8080 --check --yes", Related: "host system-status, host unregister-system"},
	"host list-systems":                    {Usage: "boetticher host list-systems", Purpose: "List saved operator-managed system registrations.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; it does not contact or change guests.", Examples: "boetticher host list-systems", Related: "host register-system, host system-status"},
	"host system-status":                   {Usage: "boetticher host system-status NAME", Purpose: "Observe one registered guest identity and its saved network policy.", Arguments: "NAME is a registered system.", Options: "No options.", Safety: "Read-only; saved intent is not reported healthy without current guest evidence.", Examples: "boetticher host system-status existing-system", Related: "host register-system"},
	"host unregister-system":               {Usage: "boetticher host unregister-system NAME --plan|--yes", Purpose: "Remove one registration's owned DHCP, DNS, firewall, and optional monitoring intent.", Arguments: "NAME is a registered system.", Options: "--plan previews; --yes approves removal and provider reconciliation.", Safety: "The guest is never modified or deleted. Removal remains possible when it is absent.", Examples: "boetticher host unregister-system existing-system --yes", Related: "host system-status"},
	"module logging":                       {Usage: "boetticher module logging query|status [flags]", Purpose: "Read a bounded VictoriaLogs view from the shared observability runtime.", Arguments: "query accepts filters only as flags; status accepts no positional arguments.", Options: "query supports --host, --unit, --level, --since up to 168h, and --limit 1-500 (default 100).", Safety: "Read-only; values are fixed quoted LogsQL literals, the owned lab-monitor-01 guest is verified before execution, and no arbitrary query language is accepted.", Examples: "boetticher module logging query --host lab-dns-01 --unit blocky.service --since 1h; boetticher module logging status", Related: "module observability"},
	"module monitoring":                    {Usage: "boetticher module monitoring status", Purpose: "Inspect metrics and Grafana in the shared observability runtime.", Arguments: "No positional arguments.", Options: "No lifecycle options.", Safety: "Read-only; module observability owns the LXC, providers, secrets, and teardown.", Examples: "boetticher module monitoring status", Related: "module observability"},
	"module statuspage":                    {Usage: "boetticher module statuspage status", Purpose: "Inspect Gatus in the shared observability runtime.", Arguments: "No positional arguments.", Options: "No lifecycle options.", Safety: "Read-only; module observability owns the LXC, providers, secrets, and teardown.", Examples: "boetticher module statuspage status", Related: "module observability"},
	"module observability":                 {Usage: "boetticher module observability plan|apply|status|test|teardown|secrets [--yes] [--public-domain DOMAIN] [--holmes-model MODEL]", Purpose: "Own the atomic shared monitoring runtime, provider payload, credentials, and lifecycle.", Arguments: "The shared lab-monitor-01 runtime carries metrics, logs, Grafana, Gatus, and optional explicitly configured Holmes/Bifrost.", Options: "--yes approves lifecycle changes; --plan previews teardown; --public-domain sets the Caddy DNS name on apply or validates it on plan; --holmes-model explicitly enables Holmes/Bifrost for the chosen provider model.", Safety: "All required secrets must already be present before guest creation. No model route is enabled or credential is generated implicitly.", Examples: "boetticher module observability plan --public-domain example.com; boetticher module observability apply --public-domain example.com --yes; boetticher module observability apply --public-domain example.com --holmes-model openai/gpt-4.1-mini --yes", Related: "module monitoring"},
	"module aiops":                         {Usage: "boetticher module aiops ask QUESTION [--yes] [--json]", Purpose: "Ask the installed read-only Holmes investigation engine one question.", Arguments: "QUESTION is one bounded operator question.", Options: "--yes approves a request that may incur model charges; --json emits a machine-readable answer.", Safety: "The ask is sent through loopback Bifrost using the separate Holmes client credential.", Examples: "boetticher module aiops ask 'Why did DNS latency rise?'", Related: "module observability"},
	"module observability alerts pushover": {Usage: "boetticher module observability alerts pushover apply|status|test|remove [flags]", Purpose: "Configure or explicitly test the optional Pushover alert contact.", Arguments: "apply changes intent and can import a bounded user:API credential file; test reads a user:API credential file without saving it; status never displays keys.", Options: "apply accepts --credentials-file, --enabled, --title, and priority -2..1 with --yes; test requires --credentials-file and --yes to send without prompting; remove requires --yes.", Safety: "Disabled or unconfigured Pushover is inert. Configuration activation waits for module observability apply; test sends one clearly labelled normal-priority notification and never retries.", Examples: "boetticher module observability alerts pushover apply --credentials-file ~/.secrets/btcr-pushover.key --yes; boetticher module observability alerts pushover status; boetticher module observability alerts pushover test --credentials-file ~/.secrets/btcr-pushover.key", Related: "module observability"},
	"controller": {
		Usage: "boetticher controller bootstrap|status|reboot [--operator USER] [--confirm-key-login] [--yes]", Purpose: "Bootstrap, inspect, or explicitly reboot the local Controller.", Arguments: "bootstrap configures locally; status reads local readiness; reboot requires --yes and never contacts Proxmox.", Options: "--operator selects the existing local operator account; bootstrap requires --confirm-key-login; reboot requires --yes.", Safety: "Bootstrap and status are local. Controller reboot is explicit and does not reboot the Host.", Examples: "boetticher controller bootstrap --operator pi --confirm-key-login; boetticher controller status; boetticher controller reboot --yes", Related: "host",
	},
	"controller bootstrap": {
		Usage: "boetticher controller bootstrap [--operator USER] [--confirm-key-login]", Purpose: "Configure the local Controller and run final local readiness checks.", Arguments: "No positional arguments.", Options: "--operator selects the existing local operator account; --confirm-key-login confirms that a fresh public-key SSH session was tested.", Safety: "Local-only and retryable. It does not enroll or deploy the Host. A reboot is never automatic; repeat bootstrap after reconnecting.", Examples: "boetticher controller bootstrap --operator pi --confirm-key-login", Related: "controller status",
	},
	"controller status": {
		Usage: "boetticher controller status [--operator USER]", Purpose: "Read local controller readiness without repairing or contacting Proxmox.", Arguments: "No positional arguments.", Options: "--operator selects the local account whose effective SSH policy is checked.", Safety: "Read-only. It does not install packages, run Ansible, change LEDs, load a site, or contact a remote system.", Examples: "boetticher controller status", Related: "controller bootstrap",
	},
	"controller reboot": {
		Usage: "boetticher controller reboot --yes", Purpose: "Reboot the local Controller for an approved persistence rehearsal.", Arguments: "No positional arguments.", Options: "--yes is required.", Safety: "Reboots only the local Controller; the Host and its guests are not contacted.", Examples: "boetticher controller reboot --yes", Related: "controller status, host status",
	},
	"host": {
		Usage: "boetticher host create-identity|show-public-key|import-host-key|enroll|apply|status|plan-storage|teardown|reboot ...", Purpose: "Bind, configure, inspect, rebuild, or reboot the single supported Proxmox Host.", Arguments: "create-identity and show-public-key manage the persistent Controller identity; import-host-key records the independently verified Host key; enroll binds the Host; apply owns the Host baseline, storage, and virtual network; status is read-only; teardown removes exact Boetticher-owned Host configuration; reboot requires --yes.", Options: "import-host-key takes --address and --key; apply takes --data-disk, --adopt-existing-network, and --yes; status accepts --details.", Safety: "Trust is never accepted automatically. Host apply stops at missing enrollment, destructive storage, or ambiguous network adoption. It never deploys Modules or changes the protected HOME path.", Examples: "boetticher host create-identity; boetticher host show-public-key; boetticher host import-host-key --address 192.0.2.10 --key 'ssh-ed25519 VERIFIED_KEY'; boetticher host enroll root@192.0.2.10; boetticher host apply --data-disk /dev/disk/by-id/DEVICE --yes; boetticher host status --details", Related: "controller status, module",
	},
	"module firewall": {
		Usage: "boetticher module firewall plan|apply|status|reboot|test|teardown [flags]", Purpose: "Plan, apply, inspect, reboot, test, or remove the first-party firewall capability.", Arguments: "The firewall capability reads the installed Host configuration and manages one bounded provider appliance plus six LAB IPv4 gateways. Packet acceptance uses temporary Controller-requested Host namespaces and never changes provider policy.", Options: "--yes approves apply, provider reboot, test, or destructive teardown; teardown also accepts --plan; test accepts --plan or --cleanup-only --yes.", Safety: "Plan, status, test --plan, and teardown --plan are read-only. The packet test is fixed, bounded, independently expected, and always cleans up its temporary fixtures. Teardown preserves Host trust, storage, vmbr0, vmbr1, and physical networking.", Examples: "boetticher module firewall plan; boetticher module firewall apply --yes; boetticher module firewall status; boetticher module firewall test --plan; boetticher module firewall test --yes; boetticher module firewall test --cleanup-only --yes; boetticher module firewall teardown --plan; boetticher module firewall teardown --yes", Related: "host apply, host status, module",
	},
	"module firewall plan": {
		Usage: "boetticher module firewall plan", Purpose: "Preview exact firewall provider and policy changes using read-only Host and provider inspection.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only. A semantic no-change result means no provider disk, runtime, or owned UCI section change is required.", Examples: "boetticher module firewall plan", Related: "module firewall apply, module firewall status",
	},
	"module firewall apply": {
		Usage: "boetticher module firewall apply [--yes]", Purpose: "Build, establish, and verify the owned firewall capability provider and six LAB gateways.", Arguments: "No positional arguments.", Options: "--yes approves creation or changes; omit it to review the normal confirmation prompt.", Safety: "Uses the installed Controller payload and strict enrolled Host trust. It never changes physical networking, DHCP, DNS, NTP, VPN, or unrelated guests.", Examples: "boetticher module firewall apply --yes", Related: "module firewall plan, module firewall status",
	},
	"module firewall status": {
		Usage: "boetticher module firewall status", Purpose: "Read the firewall capability provider's coarse operational state.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only and observational; it never runs the packet acceptance suite or repairs an absent provider. Absence is reported with a nonzero exit and no PASS claim.", Examples: "boetticher module firewall status", Related: "module firewall plan|apply|status|teardown|reboot, module firewall test",
	},
	"module firewall reboot": {
		Usage: "boetticher module firewall reboot --yes", Purpose: "Reboot only the owned firewall provider and wait for its bounded runtime recovery.", Arguments: "No positional arguments.", Options: "--yes is required.", Safety: "The Proxmox Host and Controller are not rebooted.", Examples: "boetticher module firewall reboot --yes", Related: "module firewall status, module firewall test",
	},
	"module firewall test": {
		Usage: "boetticher module firewall test [--yes|--plan|--cleanup-only --yes]", Purpose: "Exercise the fixed routed IPv4 Phase 4A firewall suite against the appliance already present.", Arguments: "The suite uses one temporary network namespace, veth pair, VLAN access port, static test address, listener, and default route per TRANSIT, INFRA, SERVERS, TRUSTED, SANDBOX, and MGMT zone.", Options: "--yes approves the bounded run; --plan previews only; --cleanup-only --yes removes only recognised leftovers. --plan cannot be combined with --yes or --cleanup-only.", Safety: "The test never applies, repairs, reboots, or tears down the firewall. Expected outcomes are independent of the renderer; transport, setup, listener, and target failures are not successful deny results. Automatic cleanup is required for PASS.", Examples: "boetticher module firewall test --plan; boetticher module firewall test --yes; boetticher module firewall test --cleanup-only --yes", Related: "module firewall status, module firewall teardown",
	},
	"module firewall teardown": {
		Usage: "boetticher module firewall teardown [--plan|--yes]", Purpose: "Preview or remove exactly the owned firewall capability provider, disk, credential, and pinned TLS trust.", Arguments: "No positional arguments.", Options: "--plan is read-only; --yes approves removal.", Safety: "Preserves Controller identity, Host trust, Proxmox installation, storage, vmbr0, vmbr1, physical networking, and unrelated guests and volumes. Already-absent teardown is a successful no-op with --yes.", Examples: "boetticher module firewall teardown --plan; boetticher module firewall teardown --yes", Related: "module firewall status, host status",
	},
	"host enroll": {
		Usage: "boetticher host enroll root@IPv4", Purpose: "Verify and bind the supported Proxmox Host to the Controller.", Arguments: "The target must be root@IPv4 and must match the imported Host key.", Options: "No options.", Safety: "Read-only remote checks plus one local /etc/boetticher/lab.yml binding. It does not apply Host configuration or deploy Modules.", Examples: "boetticher host enroll root@192.0.2.10", Related: "host status, host apply",
	},
	"host status": {
		Usage: "boetticher host status [--details]", Purpose: "Read the complete enrolled Proxmox Host state.", Arguments: "No positional arguments.", Options: "--details includes guests, storage, stable disks, LVM, mounts, interfaces, bridges, and routes.", Safety: "Read-only. It never repairs or changes the Host.", Examples: "boetticher host status; boetticher host status --details", Related: "host enroll, host apply",
	},
	"host apply": {
		Usage: "boetticher host apply [--data-disk /dev/disk/by-id/DEVICE] [--physical-trunk IFACE] [--adopt-existing-network] [--yes]", Purpose: "Inspect and establish the owned Host baseline, storage, and internal network.", Arguments: "No positional arguments.", Options: "--data-disk binds the exact stable disk at the destructive storage boundary; --physical-trunk selects one physical Ethernet interface and records its permanent MAC; --adopt-existing-network approves a compatible unowned internal bridge; --yes approves ordinary changes.", Safety: "Idempotent and fail-closed. It never accepts Host trust automatically, adopts ambiguous state, deploys Modules, or changes HOME management.", Examples: "boetticher host apply; boetticher host apply --data-disk /dev/disk/by-id/DEVICE --yes; boetticher host apply --physical-trunk nic1 --adopt-existing-network --yes", Related: "host status, host plan-storage",
	},
	"host plan-storage": {
		Usage: "boetticher host plan-storage", Purpose: "Preview the dedicated Host data-storage candidate without changing it.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only. It shows the protected boot disk, stable identities, and any exact candidate for Host apply.", Examples: "boetticher host plan-storage", Related: "host apply, host teardown",
	},
	"host teardown": {
		Usage: "boetticher host teardown [--plan] [--data-disk /dev/disk/by-id/DEVICE] [--yes]", Purpose: "Remove exact Boetticher-owned Host configuration while preserving trust, recovery, boot storage, and HOME management.", Arguments: "--plan is read-only; --data-disk must match the configured dedicated disk when it will be erased.", Options: "--yes approves ordinary removal; the disk binding is still required for destructive storage removal.", Safety: "Unknown guests, storage, bridges, and configuration stop the operation. Teardown is retryable and preserves the imported Host key trust.", Examples: "boetticher host teardown --plan; boetticher host teardown --data-disk /dev/disk/by-id/DEVICE --yes", Related: "host apply, host status",
	},
	"host reboot": {
		Usage: "boetticher host reboot --yes", Purpose: "Reboot the enrolled Proxmox Host after an explicit approval.", Arguments: "No positional arguments.", Options: "--yes is required.", Safety: "Requires a matching enrolled Host and empty guest inventory; it never reboots the Controller.", Examples: "boetticher host reboot --yes", Related: "host status, controller reboot",
	},
	"tui": {
		Usage: "boetticher tui [--site DIR] [--offline]", Purpose: "Open the experimental interactive dashboard.", Arguments: "No positional arguments.", Options: "--site selects your private site directory; --offline skips live refresh and shows saved settings.", Safety: "The dashboard launches the same commands as the CLI, so changes still ask for their normal confirmation. Secrets are never command arguments. Use the direct CLI for the supported Controller/Host and Module commands.", Examples: "boetticher tui --site ./my-boetticher", Related: "host status, module firewall",
	},
	"init": {
		Usage: "boetticher init [--site-dir DIR] [--age-identity PATH] [--root-age-identity PATH] [--external-firewall] [--storage-profile single-disk|dedicated-data-disk] [--storage-device /dev/disk/by-id/DEVICE]", Purpose: "Create a site directory and the recovery material Boetticher needs.", Arguments: "No positional arguments.", Options: "--site-dir selects the site directory; --age-identity selects your routine private age identity; --root-age-identity selects a distinct root-recovery identity that must be kept offline; --external-firewall says that you run the gateway yourself; --storage-profile selects the fixed disk layout; --storage-device is required only for dedicated-data-disk and must be one stable by-id path.", Safety: "Creates local files only. It does not contact or change Proxmox or format the selected data disk.", Examples: "boetticher init --site-dir ./my-boetticher --storage-profile dedicated-data-disk --storage-device /dev/disk/by-id/ata-example-data", Related: "storage initialize, config validate, enroll",
	},
	"enroll": {
		Usage: "boetticher enroll [--site DIR] [--bootstrap-address ADDRESS] [--operator-key PATH] [--age-identity PATH] [--recovery-confirmed] [--storage-confirmed] [--known-hosts PATH] [--proxmox-ca PATH] [--initial-user USER] [--insecure] [--trunk-interface IFACE] [--replace-scoped-credentials] [--dry-run]", Purpose: "Enroll the controller with the Proxmox host and prepare authenticated scoped access.", Arguments: "No positional arguments.", Options: "--bootstrap-address records the fresh Proxmox HOME-side address on first enrollment; --operator-key selects the public key whose matching private key reaches the fresh host; --known-hosts selects the independently verified address-key file; --proxmox-ca selects the Proxmox API CA; --initial-user, --insecure, --trunk-interface, and --replace-scoped-credentials are advanced enrollment controls; recovery and storage confirmations approve the independent recovery copy and selected data disk; --dry-run performs no remote mutation.", Safety: "This is the bounded setup operation. It does not build appliance images; normal deployment consumes a separately signed release bundle. Enrollment never arms deployment-only root authority.", Examples: "boetticher enroll --site ./my-boetticher --bootstrap-address 192.0.2.10 --operator-key ~/.ssh/id_ed25519.pub --known-hosts ~/.ssh/known_hosts --recovery-confirmed --proxmox-ca /path/to/pve-root-ca.pem", Related: "init, bundle import, plan",
	},
	"plan": {
		Usage: "boetticher plan [--site DIR] [--live] [--json]", Purpose: "Render the exact desired deployment plan and its digest without applying it.", Arguments: "No positional arguments.", Options: "--live includes read-only observations from the target; --json emits the plan and digest for automation.", Safety: "Read-only. A live plan is the approval input for deploy and becomes stale if the observed target changes.", Examples: "boetticher plan --site ./my-boetticher --live --json", Related: "deploy, status, module configure",
	},
	"bundle": {
		Usage: "boetticher bundle inspect|import PATH [--site DIR] [--json]", Purpose: "Inspect or install a signed, release-built appliance bundle.", Arguments: "PATH is a local release bundle file.", Options: "inspect reads only the unsigned manifest for diagnostics; import verifies the signature, compatibility, every digest, and every declared file before activation.", Safety: "Import is local and atomic. A missing trust root, invalid signature, mismatched controller, or incomplete bundle is rejected before activation.", Examples: "boetticher bundle inspect ./boetticher-0.1.0.tar.gz; boetticher bundle import ./boetticher-0.1.0.tar.gz --site ./my-boetticher", Related: "update, plan, deploy",
	},
	"recover": {
		Usage: "boetticher recover storage ...", Purpose: "Run the explicitly guarded recovery operation for the known Boetticher-owned storage path.", Arguments: "The storage subcommand identifies the bounded recovery operation and its exact configured device.", Options: "Recovery-specific options are shown by the selected storage operation.", Safety: "Advanced and destructive where stated. Recovery proves ownership, requires explicit confirmation, and records cleanup failures.", Examples: "boetticher recover storage --help", Related: "status --details, deploy",
	},
	"companion": {
		Usage: "boetticher companion add|setup|status|migrate ...", Purpose: "Add and manage an external Boetticher Companion after the core lab is established.", Arguments: "add records the physical eth0 MAC; setup and status use its derived SERVERS address; migrate removes an exact legacy StreamDeck guest.", Options: "Companion desired state, platform deployment, and Pi provisioning remain separate operations.", Safety: "The Companion remains outside the Proxmox module and credential boundary. Adding it never deploys; setup reaches only its fixed reservation through the enrolled bastion.", Examples: "boetticher companion add --mac DC:A6:32:E9:DD:82 --confirm --site ./my-boetticher", Related: "deploy, companion setup, companion status",
	},
	"companion add": {
		Usage: "boetticher companion add --mac MAC [--display=BOOL] [--streamdeck=BOOL] [--pulse-agent=BOOL] [--streamdeck-serial SERIAL] [--site DIR] [--dry-run] [--confirm]", Purpose: "Record one external Companion and its attached display capabilities.", Arguments: "No positional arguments.", Options: "--mac is the physical Ethernet MAC; display, streamdeck, and pulse-agent default on when first added. Omitted capability flags preserve existing settings. --streamdeck-serial selects one exact supported device. --dry-run previews; --confirm saves desired state.", Safety: "Changes site.yml only. Run deploy to apply the reservation and separate Companion tokens, then companion setup.", Examples: "boetticher companion add --mac DC:A6:32:E9:DD:82 --confirm --site ./my-boetticher", Related: "network trunk attach, deploy, companion setup, dhcp status",
	},
	"companion setup": {
		Usage: "boetticher companion setup [--site DIR] [--age-identity PATH] [--user USER] [--identity-file PATH] [--known-hosts PATH] [--host-key KEY] [--port PORT] [--confirm] [--dry-run]", Purpose: "Configure the fixed display, StreamDeck, and optional Pulse-agent capabilities on an added Raspberry Pi.", Arguments: "No positional arguments; the target is the fixed Companion SERVERS reservation.", Options: "--site selects the private site; --age-identity selects the operator-owned Age identity; --user, --identity-file, --known-hosts, --host-key, and --port define the strict SSH route; --dry-run validates without changes; --confirm authorizes remote mutation.", Safety: "Advanced and live. Setup connects through the enrolled Proxmox bastion, pins the Companion host key, and sends no Proxmox credentials to the Pi. The Pi receives only its configured capabilities and scoped credentials.", Examples: "boetticher companion setup --host-key 'ssh-ed25519 VERIFIED_HOST_KEY' --site ./my-boetticher --confirm", Related: "companion add, companion status, deploy",
	},
	"companion status": {
		Usage: "boetticher companion status [--site DIR] [--user USER] [--identity-file PATH] [--known-hosts PATH] [--port PORT] [--json]", Purpose: "Read Companion service status at its configured SERVERS reservation through the enrolled bastion.", Arguments: "No positional arguments.", Options: "--site selects the private site; --user, --identity-file, --known-hosts, and --port define the strict SSH route; --json emits machine-readable service status.", Safety: "Read-only. It requires the added Companion identity and enrolled host key and does not change the Companion, Proxmox, or site state.", Examples: "boetticher companion status --site ./my-boetticher --json", Related: "companion add, companion setup, status --details",
	},
	"companion migrate": {
		Usage: "boetticher companion migrate ADDRESS [--site DIR] [--age-identity PATH] [--proxmox-ca PATH] [--insecure] [--confirm] [--dry-run]", Purpose: "Move an existing 0.4 StreamDeck installation out of Proxmox and into the companion capability.", Arguments: "ADDRESS is the configured Proxmox IPv4 address.", Options: "--site and --age-identity select local state; --proxmox-ca and --insecure select the authenticated API TLS policy; --dry-run previews local cleanup; --confirm authorizes exact remote removal.", Safety: "Advanced and destructive. It accepts only VMID 220 with the exact lab-streamdeck-01 name, hostname, and Boetticher ownership tags, removes only its USB-export manifest, and verifies the guest is absent. Unknown or mismatched guests stop the migration.", Examples: "boetticher companion migrate 192.0.2.10 --site ./my-boetticher --confirm", Related: "companion setup, bundle import, deploy",
	},
	"deploy": {
		Usage: "boetticher deploy [--plan DIGEST] [--site DIR] [--age-identity PATH] [--dry-run] [--only-module NAME] [--replace-firewall] [--recreate-legacy-lxcs] [--confirm]", Purpose: "Apply the authenticated release bundle to an exact live plan.", Arguments: "DIGEST is the immutable digest printed by boetticher plan --live. Interactive operators may omit it and approve the live plan when prompted; non-interactive runs must provide it.", Options: "--only-module limits appliance replacement and runtime configuration to one enabled optional module while leaving core/network state unchanged; --dry-run validates local state without connecting; --replace-firewall and --recreate-legacy-lxcs are advanced recovery actions and require --confirm.", Safety: "This is the only normal command that changes the platform. It requires a signed compatible release, rechecks live observations before mutation, journals apply/verify/cleanup/commit boundaries, and fails closed on cleanup errors.", Examples: "boetticher deploy --site ./my-boetticher; boetticher deploy --only-module gatus --plan sha256:... --site ./my-boetticher", Related: "bundle import, plan, status",
	},
	"status": {
		Usage: "boetticher status [--site DIR] [--ssh-config PATH] [--age-identity PATH] [--ssh-journey] [--live] [--details] [--json]", Purpose: "Show the consolidated read-only operational view.", Arguments: "No positional arguments.", Options: "--live adds read-only gateway, Smallstep CA, and leaf-certificate checks; --age-identity selects the routine Age identity needed to inspect retained AirVPN metadata; --ssh-journey tests the configured bastion route; --ssh-config selects generated SSH settings; --details adds reasons and safe next actions; --json is for tools. Exit status is zero only for HEALTHY.", Safety: "Read-only. A broken connection or malformed response returns a non-zero result; it never repairs or changes infrastructure.", Examples: "boetticher status --site ./my-boetticher --details --live; boetticher status --site ./my-boetticher --details --live --json", Related: "deploy, plan, dhcp",
	},
	"update": {
		Usage: "boetticher update [--bundle PATH] [--site DIR] [--dry-run] [--confirm]", Purpose: "Import a signed release bundle or update compatible v3 site settings for platform 0.1.0 without deploying them.", Arguments: "PATH is the local signed release bundle when --bundle is supplied; otherwise there are no positional arguments.", Options: "--bundle imports an authenticated release bundle and cannot be combined with --dry-run or --confirm; --dry-run validates and prints the desired-state update without writing; --confirm saves the updated site and generated config.", Safety: "Update never deploys. Bundle import and desired-state writes are local and atomic; if refreshing generated config fails, the original site.yml stays in place.", Examples: "boetticher update --bundle ./boetticher-0.1.0.tar.gz --site ./my-boetticher; boetticher update --site ./my-boetticher --dry-run; boetticher update --site ./my-boetticher --confirm", Related: "bundle import, deploy, status, config validate",
	},
	"logs": {
		Usage: "boetticher logs [HOST] [--site DIR] [--unit UNIT] [--since DURATION] [--priority LEVEL] [--limit N]", Purpose: "Read a small journal view through the optional central collector and bastion.", Arguments: "HOST is a known Boetticher endpoint; omit it for the collector's own journal.", Options: "--site selects your site directory; --unit accepts a systemd unit such as blocky or blocky.service; --since accepts up to 168h; --priority selects a journal level; --limit is 1-500 and defaults to 100.", Safety: "Read-only. There is no follow mode, arbitrary journal path, or query language. Logs arrive asynchronously, so a service does not wait for logging to stay available.", Examples: "boetticher logs lab-dns-01 --site ./my-boetticher --unit blocky --since 1h; boetticher logs lab-fw-01 --priority warning --limit 100", Related: "status --details, module list",
	},
	"aiops": {
		Usage: "boetticher aiops status [--site DIR] [--live] [--json]", Purpose: "Show AIOps incident activity and usage.", Arguments: "status is the only operation.", Options: "--live reads the adapter through the normal bastion; --json is for tools.", Safety: "Read-only. It will not start an investigation, write a note, acknowledge an alert, restart anything, or remediate a service.", Examples: "boetticher aiops status --site ./my-boetticher --live", Related: "module list, status --details, logs",
	},
	"ssh-config": {
		Usage: "boetticher ssh-config [--site DIR] [--output PATH| -] [--force] [--check] [--identity-file PATH] [--install-include]", Purpose: "Create or check an SSH config that knows the bastion route.", Arguments: "No positional arguments.", Options: "--check checks an existing file; --output selects a file or -; --force permits replacing the generated file; --install-include adds the user SSH include.", Safety: "Writes only the file you select. Inspect the path before using --force.", Examples: "boetticher ssh-config --site ./my-boetticher --check", Related: "access, logs, status --details",
	},
	"access": {
		Usage: "boetticher access [--site DIR]", Purpose: "List the URLs and access routes for enabled platform services.", Arguments: "No positional arguments.", Options: "--site selects your site directory.", Safety: "Read-only and non-secret. Use the CLI, Proxmox, and service UIs for normal administration. If you run an external firewall, you manage it yourself. Logging lives behind boetticher logs, not a web UI.", Examples: "boetticher access --site ./my-boetticher", Related: "logs, ssh-config, status --details",
	},
	"network": {
		Usage: "boetticher network trunk status|attach|detach [INTERFACE] [--site DIR] [--confirm] [--live] [--age-identity PATH] [--proxmox-ca PATH] [--insecure]", Purpose: "Inspect or explicitly change the physical VLAN trunk, while staying virtual-only by default.", Arguments: "INTERFACE is required for attach and detach and must match the observed hardware.", Options: "--live queries Proxmox; --confirm approves a live trunk change; connection options select the certificate path.", Safety: "A physical trunk change can cut off management. Virtual-only sites leave spare NICs alone until you choose one.", Examples: "boetticher network trunk status --site ./my-boetticher --live", Related: "enroll, firewall, status --details",
	},
	"hardware": {
		Usage: "boetticher hardware usb list|status|bind|unbind [MODULE REQUIREMENT [PORT]] [--site DIR] [--live] [--confirm] [--age-identity PATH] [--proxmox-ca PATH] [--insecure]", Purpose: "Inspect USB hardware and bind a module to a stable physical port.", Arguments: "status can filter MODULE REQUIREMENT; bind needs MODULE REQUIREMENT PORT; unbind needs MODULE REQUIREMENT.", Options: "--live reads parent USB identities from Proxmox; --confirm saves the binding and invokes deploy; connection options select the certificate path.", Safety: "Bindings use a physical port and known device identity, never a changing device path, VMID, or your workload.", Examples: "boetticher hardware usb bind MODULE REQUIREMENT 1-2.4 --confirm --site ./my-boetticher", Related: "module, deploy, status --details",
	},
	"pki": {
		Usage: "boetticher pki client create|export|revoke NAME [--site DIR] [--output PATH] [--age-identity PATH]", Purpose: "Create, export, or revoke browser and device client certificates.", Arguments: "NAME is a short client name; certificate-chain export has no client name.", Options: "--output selects an export path; --age-identity selects the independent recovery identity; --site selects local settings.", Safety: "Private keys are never printed to stdout. Certificate actions update local generated config only.", Examples: "boetticher pki client create operator --site ./my-boetticher", Related: "access, deploy, status --details",
	},
	"pki trust": {
		Usage: "boetticher pki trust export [--site DIR] [--output PATH| -] [--format pem|apple] [--age-identity PATH]", Purpose: "Export the public Boetticher trust chain or an Apple configuration profile.", Arguments: "No positional arguments.", Options: "--format selects PEM (the default) or an Apple trust profile; --output selects a file or - for stdout; --age-identity selects the independent recovery identity; --site selects local settings.", Safety: "Writes public certificates only. The private CA key never leaves the controller.", Examples: "boetticher pki trust export --site ./my-boetticher --format apple --output ./boetticher-trust.mobileconfig", Related: "pki client create, access",
	},
	"firewall": {
		Usage: "boetticher firewall status|show|diff|counters|logs|verify [--site DIR] [--age-identity PATH] [--live] [--json] [--format FORMAT] [--zone ZONE] [--limit N]", Purpose: "Look at the managed gateway rules, counters, and logs without changing them.", Arguments: "Subcommands select a read-only view; firewall logs can take a zone and limit.", Options: "--live queries the managed firewall; --age-identity selects the routine Age identity needed to inspect retained AirVPN metadata; --json is for tools; show accepts --format human|nft; logs accepts --zone and --limit 1-1000.", Safety: "These views do not edit nftables, DHCP, or routes. If you use an external gateway, it stays yours to manage. Use the rule commands to add your workload exceptions.", Examples: "boetticher firewall diff --site ./my-boetticher --live", Related: "dhcp, network, logs, status --details",
	},
	"firewall rule add": {
		Usage: "boetticher firewall rule add [--source SOURCE] [--destination DESTINATION|--vmid VMID] [--protocol PROTOCOL] [--ports PORTS] [--id ID] [--site DIR] [--dry-run] [--confirm] [--json]", Purpose: "Add one precise firewall allowance for your workload.", Arguments: "--source and --protocol are required; choose exactly one of --destination and --vmid.", Options: "--dry-run previews the change; --confirm saves it; --age-identity, --proxmox-ca, and --insecure apply when looking up a VMID.", Safety: "Changes site.yml only; deploy applies it. Core destinations remain unavailable except one reserved SERVERS /32 to Pulse on TCP/443. Review the rule before confirming.", Examples: "boetticher firewall rule add --source TRUSTED --destination 10.10.20.61 --protocol tcp --ports 8080 --confirm --site ./my-boetticher; boetticher firewall rule add --source 10.10.20.50/32 --destination 10.10.10.20/32 --protocol tcp --ports 443 --id ufr-lab-display-pulse --confirm --site ./my-boetticher", Related: "firewall diff, deploy, dhcp reservation",
	},
	"firewall rule list": {
		Usage: "boetticher firewall rule list [--site DIR] [--json]", Purpose: "List user-workload firewall rules recorded in the site.", Arguments: "No positional arguments.", Options: "--json emits machine-readable rules; --site selects local state.", Safety: "Read-only. It does not change firewall policy or deploy anything.", Examples: "boetticher firewall rule list --site ./my-boetticher", Related: "firewall rule add, firewall rule remove",
	},
	"firewall rule remove": {
		Usage: "boetticher firewall rule remove --id ID [--site DIR] [--dry-run] [--confirm] [--json]", Purpose: "Remove a user-workload firewall rule from desired site configuration.", Arguments: "--id is required.", Options: "--dry-run previews the change; --confirm writes it; --json emits machine-readable output.", Safety: "Changes site.yml only and never deploys. Review the rule before confirming; deployment remains boetticher deploy.", Examples: "boetticher firewall rule remove --id ufr-example --confirm --site ./my-boetticher", Related: "firewall rule list, deploy",
	},
	"module dhcp": {
		Usage: "boetticher module dhcp plan|apply|status|teardown|test|add-reservation|remove-reservation|list-reservations|list-leases [flags]", Purpose: "Manage client DHCP allocation, reservation-derived names, and client-facing NTP on the shared firewall appliance.", Arguments: "Reservations are desired state; leases are read-only native runtime state.", Options: "apply, teardown, test, and resource changes accept --yes; test also accepts --plan or --cleanup-only --yes; plan and list operations are read-only.", Safety: "Uses installed lab.yml and the shared appliance mutation lock; it never fabricates a lease or creates another appliance.", Examples: "boetticher module dhcp plan; boetticher module dhcp apply --yes; boetticher module dhcp add-reservation app --zone TRUSTED --mac 02:00:00:00:30:01 --address 10.10.30.61 --yes", Related: "module dns, module firewall",
	},
	"module dns": {
		Usage: "boetticher module dns plan|apply|status|teardown|test|add-record|remove-record|list-records [flags]", Purpose: "Manage local A/CNAME names and authenticated encrypted upstream DNS on the shared firewall appliance.", Arguments: "Names may be short local names; results display canonical lab.home.arpa names.", Options: "apply, teardown, test, and resource changes accept --yes; test also accepts --plan or --cleanup-only --yes; plan and list operations are read-only.", Safety: "Uses verified appliance management with Quad9 DoT and no plaintext fallback or private site credentials.", Examples: "boetticher module dns plan; boetticher module dns apply --yes; boetticher module dns add-record app --type A --value 10.10.20.61 --yes", Related: "module dhcp, module firewall",
	},
	"module vpn": {
		Usage: "boetticher module vpn plan|apply|status|teardown|add-client|remove-client [--location SELECTOR] [flags]", Purpose: "Manage one retained AirVPN WireGuard connection and VPN-only egress for declared protected client reservations.", Arguments: "Clients reference existing DHCP reservations in the permanent protected address class.", Options: "apply accepts --yes, --location SELECTOR, and initial provisioning or explicit selector refresh accepts --api-key-stdin --yes; add-client and remove-client accept --yes; teardown accepts --plan or --yes; status accepts --details.", Safety: "Plan and status are observational. Account API credentials are read once from stdin, never stored in lab.yml or arguments; ordinary reapply uses retained root-only tunnel material without account access and refuses a selector mismatch. Named refreshes require healthy public provider metadata. Provider reboot and teardown inspect the enrolled Host inventory and each running QEMU/LXC NIC before stopping protection; malformed or unavailable inventory refuses the mutation. Stopped guests do not block the operation. Teardown retains client intent, protected ranges, and reusable account material, leaving protected clients blocked while disconnected. This is source and local-runtime behavior, not deployment or packet acceptance proof.", Examples: "boetticher module vpn plan; boetticher module vpn apply --api-key-stdin --yes; boetticher module vpn apply --location Sydney --api-key-stdin --yes; boetticher module vpn add-client vpn-test-trusted --yes; boetticher module vpn remove-client vpn-test-trusted --yes; boetticher module vpn status --details; boetticher module vpn teardown --plan", Related: "module firewall, module dhcp",
	},
	"module vpn plan": {
		Usage: "boetticher module vpn plan", Purpose: "Preview the exact VPN connection, source-routing, and protected-client policy changes.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only. It never contacts the AirVPN account API, writes retained tunnel material, or changes the provider.", Examples: "boetticher module vpn plan", Related: "module vpn apply, module vpn status",
	},
	"module vpn apply": {
		Usage: "boetticher module vpn apply [--yes] [--api-key-stdin] [--location SELECTOR]", Purpose: "Apply or reapply one named AirVPN WireGuard connection and fail-closed protected-client egress policy.", Arguments: "No positional arguments.", Options: "--yes approves desired and provider changes; --location selects a named server, country, or region and defaults to europe; --api-key-stdin is required with --yes for first provisioning or an explicit profile refresh.", Safety: "Uses the installed Controller configuration, authenticated Host/provider transports, permanent IPv4/IPv6 safety guard, and exact retained device identity. It never falls back to ordinary WAN for protected clients.", Examples: "boetticher module vpn apply --api-key-stdin --yes; boetticher module vpn apply --location Sydney --api-key-stdin --yes; boetticher module vpn apply --yes", Related: "module vpn status, module vpn teardown",
	},
	"module vpn status": {
		Usage: "boetticher module vpn status [--details]", Purpose: "Observe VPN connection and protected-client enforcement separately.", Arguments: "No positional arguments.", Options: "--details includes location and selected-client counts.", Safety: "Read-only. A missing or unusable connection is reported as blocked/unavailable and never repairs the killswitch.", Examples: "boetticher module vpn status --details", Related: "module vpn apply, module vpn teardown",
	},
	"module vpn teardown": {
		Usage: "boetticher module vpn teardown [--plan|--yes]", Purpose: "Disable the active VPN connection while retaining VPN-required intent and permanent protection.", Arguments: "No positional arguments.", Options: "--plan previews; --yes approves the change.", Safety: "Protected clients remain unable to use ordinary WAN; profile and account device identity are retained for deliberate reapply. Shared firewall, DNS, DHCP, Host trust, and physical networking are preserved.", Examples: "boetticher module vpn teardown --plan; boetticher module vpn teardown --yes", Related: "module vpn status, module firewall status",
	},
	"module vpn add-client": {
		Usage: "boetticher module vpn add-client RESERVATION [--yes]", Purpose: "Declare one existing DHCP reservation as VPN-only and reconcile its protected source policy.", Arguments: "RESERVATION must already exist in DHCP and use a valid protected .224-.239 address.", Options: "--yes approves the desired and provider change.", Safety: "The reservation is never copied or renumbered. The client cannot fall back to ordinary WAN, and the shared DNS/NTP exceptions remain explicit.", Examples: "boetticher module vpn add-client vpn-test-trusted --yes", Related: "module vpn apply, module dhcp list-reservations",
	},
	"module vpn remove-client": {
		Usage: "boetticher module vpn remove-client RESERVATION [--yes]", Purpose: "Remove one declared VPN-only client while preserving protected ranges and the reusable connection.", Arguments: "RESERVATION must be a current VPN client with no dependent forward.", Options: "--yes approves the desired and provider change.", Safety: "Removing client permission never grants ordinary-WAN fallback; the address-class guard remains in force.", Examples: "boetticher module vpn remove-client vpn-test-trusted --yes", Related: "module vpn add-client, module dhcp remove-reservation",
	},
	"module media": {
		Usage: "boetticher module media plan|apply|status|test|teardown [--plan|--yes] [--cloudflare-token-file FILE]", Purpose: "Manage the fixed amd64 media VM and its protected application lifecycle.", Arguments: "No positional arguments.", Options: "--plan previews apply or teardown; --yes approves mutation or the bounded test; --cloudflare-token-file supplies the operator-owned private token file for first install.", Safety: "Apply requires enabled DNS, DHCP, healthy VPN/provider state, and a complete protected-guest inventory; it never claims deployment or packet acceptance. Test reports only installed guest runtime evidence. Teardown retains media and client protection.", Examples: "boetticher module media plan; boetticher module media apply --cloudflare-token-file /secure/path/token --yes; boetticher module media test --yes; boetticher module media teardown --yes", Related: "module vpn, module observability",
	},
	"module tailnet":                 {Usage: "boetticher module tailnet plan|apply|status|test|teardown [flags]", Purpose: "Manage the fixed Tailnet subnet router in the TRANSIT zone.", Arguments: "The capability owns one unprivileged VMID 200 guest with an exact TUN device, stable TRANSIT address, and 10.10.0.0/16 route.", Options: "apply accepts --auth-key-file and --yes; test and teardown accept --plan or --yes.", Safety: "Auth keys are bootstrap-only and never saved or logged. Route approval and native preferences are checked before status can report healthy.", Examples: "boetticher module tailnet plan; boetticher module tailnet apply --auth-key-file /path/key --yes; boetticher module tailnet status", Related: "module firewall, module dns, module dhcp"},
	"module dhcp plan":               {Usage: "boetticher module dhcp plan", Purpose: "Preview DHCP scopes, reservations, NTP options, and owned provider changes.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; it does not write lab.yml or provider state.", Examples: "boetticher module dhcp plan", Related: "module dhcp apply"},
	"module dhcp apply":              {Usage: "boetticher module dhcp apply [--yes]", Purpose: "Enable and reconcile reference DHCP scopes and client-facing NTP.", Arguments: "No positional arguments.", Options: "--yes approves the desired and provider change.", Safety: "Requires an existing usable firewall and DNS capability; failed application retains saved intent.", Examples: "boetticher module dhcp apply --yes", Related: "module dhcp status, module dns apply"},
	"module dhcp status":             {Usage: "boetticher module dhcp status", Purpose: "Read DHCP scope, lease-store, and client-facing NTP readiness.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; absent and unavailable states are not reported as PASS.", Examples: "boetticher module dhcp status", Related: "module dhcp list-leases"},
	"module dhcp teardown":           {Usage: "boetticher module dhcp teardown [--plan|--yes]", Purpose: "Disable client DHCP and client-facing NTP while retaining desired reservations.", Arguments: "No positional arguments.", Options: "--plan previews; --yes approves removal.", Safety: "Preserves DNS, the firewall, Host trust, storage, and physical networking.", Examples: "boetticher module dhcp teardown --plan; boetticher module dhcp teardown --yes", Related: "module dns teardown"},
	"module dhcp test":               {Usage: "boetticher module dhcp test [--plan|--yes|--cleanup-only --yes]", Purpose: "Run bounded real-client DHCP allocation, naming, and NTP checks.", Arguments: "No positional arguments.", Options: "--plan previews; --yes approves the bounded test; --cleanup-only --yes removes only recognised test leftovers.", Safety: "Temporary namespaces/veths are independently cleaned; Host root networking and clock are untouched.", Examples: "boetticher module dhcp test --plan; boetticher module dhcp test --yes; boetticher module dhcp test --cleanup-only --yes", Related: "module dhcp status"},
	"module dhcp add-reservation":    {Usage: "boetticher module dhcp add-reservation NAME --zone ZONE --mac MAC --address IPv4 [--yes]", Purpose: "Add or confirm one desired stable client reservation and reconcile it immediately.", Arguments: "NAME, zone, stable MAC, and IPv4 address are required.", Options: "--yes approves the desired and provider change.", Safety: "Rejects malformed, conflicting, gateway, broadcast, and dynamic-pool addresses before mutation.", Examples: "boetticher module dhcp add-reservation app --zone TRUSTED --mac 02:00:00:00:30:01 --address 10.10.30.61 --yes", Related: "module dhcp list-reservations"},
	"module dhcp remove-reservation": {Usage: "boetticher module dhcp remove-reservation NAME [--yes]", Purpose: "Remove one desired reservation while allowing an existing lease to expire normally.", Arguments: "NAME is the reservation identifier.", Options: "--yes approves the desired and provider change.", Safety: "Removes only the named desired reservation; it does not fabricate or revoke a lease.", Examples: "boetticher module dhcp remove-reservation app --yes", Related: "module dhcp list-reservations"},
	"module dhcp list-reservations":  {Usage: "boetticher module dhcp list-reservations", Purpose: "List saved reservation intent with canonical names.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; it does not query or alter provider lease state.", Examples: "boetticher module dhcp list-reservations", Related: "module dhcp add-reservation"},
	"module dhcp list-leases":        {Usage: "boetticher module dhcp list-leases", Purpose: "Read actual native DHCP lease state for the DHCP capability from the persistent appliance lease file.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; reservations are not presented as leases.", Examples: "boetticher module dhcp list-leases", Related: "module dhcp list-reservations"},
	"module dns plan":                {Usage: "boetticher module dns plan", Purpose: "Preview local records, encrypted Quad9 upstreams, and owned provider changes.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; it does not write lab.yml or provider state.", Examples: "boetticher module dns plan", Related: "module dns apply"},
	"module tailnet plan":            {Usage: "boetticher module tailnet plan", Purpose: "Preview the fixed Tailnet guest and route contract.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only.", Examples: "boetticher module tailnet plan", Related: "module tailnet apply"},
	"module dns apply":               {Usage: "boetticher module dns apply [--yes]", Purpose: "Enable local naming and authenticated encrypted upstream DNS on the shared appliance.", Arguments: "No positional arguments.", Options: "--yes approves the desired and provider change.", Safety: "Requires the existing firewall; no plaintext resolver fallback is enabled.", Examples: "boetticher module dns apply --yes", Related: "module dns status, module dhcp apply"},
	"module dns status":              {Usage: "boetticher module dns status", Purpose: "Read local resolver and encrypted upstream readiness.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; absent and unavailable states are not reported as PASS.", Examples: "boetticher module dns status", Related: "module dns list-records"},
	"module dns teardown":            {Usage: "boetticher module dns teardown [--plan|--yes]", Purpose: "Disable local client DNS while retaining desired records.", Arguments: "No positional arguments.", Options: "--plan previews; --yes approves removal.", Safety: "Refuses while DHCP remains enabled and never removes the firewall or Host substrate.", Examples: "boetticher module dns teardown --plan; boetticher module dns teardown --yes", Related: "module dhcp teardown"},
	"module dns test":                {Usage: "boetticher module dns test [--plan|--yes|--cleanup-only --yes]", Purpose: "Run bounded local-record and encrypted recursive-resolution checks.", Arguments: "No positional arguments.", Options: "--plan previews; --yes approves the bounded test; --cleanup-only --yes removes only recognised test leftovers.", Safety: "Temporary client fixtures are independently cleaned and TLS verification remains enabled.", Examples: "boetticher module dns test --plan; boetticher module dns test --yes; boetticher module dns test --cleanup-only --yes", Related: "module dns status"},
	"module dns add-record":          {Usage: "boetticher module dns add-record NAME --type A|CNAME --value VALUE [--yes]", Purpose: "Add or confirm one desired local A or CNAME record and reconcile it immediately.", Arguments: "NAME, supported type, and value are required.", Options: "--yes approves the desired and provider change.", Safety: "Rejects namespace collisions and CNAME cycles before mutation.", Examples: "boetticher module dns add-record app --type A --value 10.10.20.61 --yes", Related: "module dns list-records"},
	"module dns remove-record":       {Usage: "boetticher module dns remove-record NAME [--yes]", Purpose: "Remove one desired local record by canonical name.", Arguments: "NAME is the record identifier.", Options: "--yes approves the desired and provider change.", Safety: "Removes only the named desired record and preserves DHCP reservations.", Examples: "boetticher module dns remove-record app --yes", Related: "module dns list-records"},
	"module dns list-records":        {Usage: "boetticher module dns list-records", Purpose: "List saved local A and CNAME intent with canonical names.", Arguments: "No positional arguments.", Options: "No options.", Safety: "Read-only; it does not query or alter provider state.", Examples: "boetticher module dns list-records", Related: "module dns add-record"},
	"module": {
		Usage: "boetticher module <capability> <action> [flags]", Purpose: "Manage a bounded Host capability through its ordinary operator intent.", Arguments: "The capability is the operator-managed concern, such as firewall, dhcp, dns, monitoring, or observability. NTP and DHCP-derived DNS are supporting behaviour of client services, not standalone capabilities.", Options: "Capabilities define only their implemented bounded flags; provider, appliance, daemon, and peripheral names are not public namespaces.", Safety: "Client services share the existing firewall appliance, verified management, lab.yml intent, and mutation lock.", Examples: "boetticher module firewall plan; boetticher module dns apply --yes; boetticher module dhcp apply --yes; boetticher module firewall status", Related: "host status, module firewall",
	},
	"config": {
		Usage: "boetticher config validate|show|schema [--site DIR]", Purpose: "Check, display, or find the site configuration schema.", Arguments: "validate, show, and schema select the read-only operation.", Options: "--site selects your private site directory; schema does not need a site directory.", Safety: "Read-only. Unknown fields, invalid settings, and attempts to disable mandatory modules stop before the lab changes.", Examples: "boetticher config validate --site ./my-boetticher; boetticher config schema", Related: "module list, plan, deploy --dry-run",
	},
}

var nestedHelpSpecs = map[string]helpSpec{
	"aiops status":                         helpSpecs["aiops"],
	"companion add":                        helpSpecs["companion add"],
	"companion setup":                      helpSpecs["companion setup"],
	"companion status":                     helpSpecs["companion status"],
	"companion migrate":                    helpSpecs["companion migrate"],
	"controller reboot":                    helpSpecs["controller reboot"],
	"hardware usb list":                    helpSpecs["hardware"],
	"hardware usb status":                  helpSpecs["hardware"],
	"hardware usb bind":                    helpSpecs["hardware"],
	"hardware usb unbind":                  helpSpecs["hardware"],
	"pki client create":                    helpSpecs["pki"],
	"pki client export":                    helpSpecs["pki"],
	"pki client revoke":                    helpSpecs["pki"],
	"pki trust export":                     helpSpecs["pki trust"],
	"firewall status":                      helpSpecs["firewall"],
	"firewall show":                        helpSpecs["firewall"],
	"firewall diff":                        helpSpecs["firewall"],
	"firewall counters":                    helpSpecs["firewall"],
	"firewall logs":                        helpSpecs["firewall"],
	"firewall verify":                      helpSpecs["firewall"],
	"firewall rule add":                    helpSpecs["firewall rule add"],
	"firewall rule list":                   helpSpecs["firewall rule list"],
	"firewall rule remove":                 helpSpecs["firewall rule remove"],
	"module dhcp":                          helpSpecs["module dhcp"],
	"module dns":                           helpSpecs["module dns"],
	"module logging":                       helpSpecs["module logging"],
	"module logging query":                 helpSpecs["module logging"],
	"module monitoring":                    helpSpecs["module monitoring"],
	"module statuspage":                    helpSpecs["module statuspage"],
	"module observability":                 helpSpecs["module observability"],
	"module observability alerts pushover": helpSpecs["module observability alerts pushover"],
	"module aiops":                         helpSpecs["module aiops"],
	"config validate":                      helpSpecs["config"],
	"config show":                          helpSpecs["config"],
	"config schema":                        helpSpecs["config"],
}

// CommandReferenceMarkdown renders the browseable command menu from the same
// usage data as CLI help. It is a Jekyll page for the docs site and remains
// short enough to be useful instead of becoming another manual.
func CommandReferenceMarkdown() string {
	var document strings.Builder
	document.WriteString("---\nlayout: default\ntitle: Command reference\nsection: commands\ndescription: A generated menu of every public Boetticher command form.\n---\n\n")
	document.WriteString("# Command reference\n\n")
	document.WriteString("This page is generated from the same usage menu as `boetticher help`. The Controller owns local runtime and trust; the Host owns Proxmox baseline, storage, and virtual networking; Modules provide later operator capabilities. Add `--help` to any command for the full explanation. Reapplying an already-correct Host is a successful no-op and reports `No changes required.`\n\n")
	document.WriteString("## The usual loop\n\n```text\nboetticher controller bootstrap\nboetticher controller status\nboetticher host enroll root@PROXMOX_ADDRESS\nboetticher host apply\nboetticher host status\n```\n\n")
	document.WriteString("## Normal command menu\n\n```text\n")
	for _, spec := range commandSpecs {
		document.WriteString(spec.Usage + "\n")
	}
	document.WriteString("```\n\n## Advanced command menu\n\n```text\n")
	for _, spec := range advancedCommandSpecs {
		document.WriteString(spec.Usage + "\n")
	}
	document.WriteString("```\n\n")
	document.WriteString("## Need a hand?\n\n")
	document.WriteString("```text\nboetticher help\nboetticher help --advanced\nboetticher host apply --help\nboetticher host teardown --help\nboetticher module firewall status --help\n```\n")
	return strings.TrimRight(document.String(), "\n") + "\n"
}
