[project]
name = "boetticher-streamdeck"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
  "streamdeck @ https://github.com/abcminiuser/python-elgato-streamdeck/archive/5537d6991e651d0d293000fa61ee330d6209c8e5.tar.gz",
  "Pillow==11.3.0",
  "httpx==0.28.1",
]

[project.scripts]
boetticher-streamdeck = "boetticher_streamdeck.app:main"

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
