---
- name: restart journald
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    state: restarted

- name: reload ssh
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded

- name: restart boetticher-status
  ansible.builtin.systemd_service:
    name: boetticher-status.service
    state: restarted
    daemon_reload: true
