---
- name: restart pdns
  ansible.builtin.service:
    name: pdns
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart blocky
  ansible.builtin.service:
    name: blocky
    state: restarted
