package ansible

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/gofastercloud/boetticher/internal/dns"
	"github.com/gofastercloud/boetticher/internal/model"
	"github.com/gofastercloud/boetticher/internal/zabbix"
)

func Inventory(s model.Site) (string, error) {
	if err := s.Validate(); err != nil {
		return "", err
	}
	components := s.PlatformComponents()
	var b strings.Builder
	b.WriteString("# Generated by boetticher. Do not edit.\n")
	b.WriteString("# Model revision: ")
	revision, err := s.Revision()
	if err != nil {
		return "", err
	}
	b.WriteString(revision + "\n\n")
	b.WriteString("[proxmox]\n")
	for _, component := range components {
		if component.Name == "lab-proxmox-01" {
			writeHost(&b, component, false)
		}
	}
	b.WriteString("\n[dns]\n")
	for _, component := range components {
		if component.Role == "DNS/NTP" {
			writeHost(&b, component, true)
		}
	}
	b.WriteString("\n[monitor]\n")
	for _, component := range components {
		if component.Name == "lab-monitor-01" {
			writeHost(&b, component, true)
		}
	}
	b.WriteString("\n[portal]\n")
	for _, component := range components {
		if component.Name == "lab-portal-01" {
			writeHost(&b, component, true)
		}
	}
	b.WriteString("\n[managed:children]\nproxmox\ndns\nmonitor\nportal\n\n")
	b.WriteString("[managed:vars]\nansible_connection=ssh\nansible_python_interpreter=/usr/bin/python3\nansible_host_key_checking=true\n")
	return b.String(), nil
}

func writeHost(b *strings.Builder, component model.Component, throughBastion bool) {
	user := component.SSHUser
	if user == "" {
		user = model.DefaultAdminSSHUser
	}
	fmt.Fprintf(b, "%s ansible_host=%s ansible_user=%s", component.Name, component.Address, user)
	if throughBastion {
		fmt.Fprintf(b, " ansible_ssh_common_args='-o ProxyJump=lab-bastion -o HostKeyAlias=%s.%s'", component.Hostname, model.DefaultDomain)
	} else {
		fmt.Fprintf(b, " ansible_ssh_common_args='-o HostKeyAlias=%s.%s'", component.Hostname, model.DefaultDomain)
	}
	b.WriteByte('\n')
}

func Variables(s model.Site) ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	revision, err := s.Revision()
	if err != nil {
		return nil, err
	}
	dnsPlan, err := dns.PlanFromSite(s)
	if err != nil {
		return nil, err
	}
	zabbixPlan, err := zabbix.PlanFromSite(s)
	if err != nil {
		return nil, err
	}
	value := struct {
		ModelRevision           string      `json:"model_revision"`
		Domain                  string      `json:"domain"`
		IPv4Only                bool        `json:"ipv4_only"`
		AuthoritativeDNS        string      `json:"authoritative_dns"`
		AuthoritativeDNSVersion string      `json:"authoritative_dns_version"`
		AuthoritativeDNSPort    string      `json:"authoritative_dns_port"`
		DynamicZones            []string    `json:"dynamic_zones"`
		AdGuardForwardZones     []string    `json:"adguard_forward_zones"`
		DNSPlan                 dns.Plan    `json:"dns_plan"`
		ZabbixPlan              zabbix.Plan `json:"zabbix_plan"`
	}{revision, s.Network.Domain, true, dnsPlan.Implementation, dnsPlan.ImplementationVersion, dns.AuthoritativePort, dynamicZoneNames(dnsPlan.DynamicZones), dnsPlan.AdGuardForwardZones, dnsPlan, zabbixPlan}
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func dynamicZoneNames(zones []dns.DynamicZone) []string {
	result := make([]string, 0, len(zones))
	for _, zone := range zones {
		result = append(result, zone.Name)
	}
	return result
}

// Run executes ansible-playbook with model variables over stdin. This keeps
// the invocation free of secret values and avoids a plaintext extra-vars
// file. The playbook itself must obtain any future secret material through an
// approved runtime mechanism.
func Run(ctx context.Context, playbook, inventory string, variables []byte) error {
	if playbook == "" || inventory == "" {
		return errors.New("Ansible playbook and inventory are required")
	}
	executable, err := exec.LookPath("ansible-playbook")
	if err != nil {
		return fmt.Errorf("ansible-playbook is required: %w", err)
	}
	command := exec.CommandContext(ctx, executable, "-i", inventory, playbook, "--extra-vars", "@-")
	command.Stdin = strings.NewReader(string(variables))
	command.Env = append(os.Environ(), "ANSIBLE_HOST_KEY_CHECKING=True")
	if _, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("ansible-playbook failed: %w", err)
	}
	return nil
}
